Add automatic evaluation
pal03377/Athena-New pull request #174
Opened 2023-11-05 21:01 UTC by FelixTJDietrich

### Motivation and Context

We want an option to systematically evaluate the modules without manual labor. 

closes #84 
closes #36 

### Description

- [ ] Add LLM-as-a-judge for text modules
- [ ] Add eval code for SGi evaluation
- [ ] Add token usage and response times in evaluation response

### Steps for Testing

### Screenshots

2023-11-08 19:27 UTC, pal03377 reviewed
I looked through the code already. I will test everything later as well.

2023-11-08 19:27 UTC, pal03377 commented on athena/athena/endpoints.py
> +            feedback.meta.update(get_stored_feedback_meta(feedback) or {})
```suggestion
        for feedback in true_feedbacks + predicted_feedbacks:
            feedback.meta.update(get_stored_feedback_meta(feedback) or {})
```

2023-11-08 19:27 UTC, pal03377 commented on module_example/module_example/__main__.py
> +# Only if it makes sense for a module (Optional)
Very good that you included an eval endpoint to the example module! This will help future developers in their understanding, I believe.

2023-11-08 19:27 UTC, pal03377 commented on module_text_llm/module_text_llm/evaluation.py
> +        suggestions_with_grading_instructions)
I think you can directly write out the `len(...)` twice. This looks like a micro-optimization to me.

2023-11-08 19:27 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/utils.py
> +def get_line_range_from_index_range(index_start: Optional[int], index_end: Optional[int], content: str) -> Tuple[Optional[int], Optional[int]]:
Do this function and the one before make sense in a more general utils file in the `athena` package? They seem useful.

2023-11-08 19:27 UTC, pal03377 commented on playground/src/hooks/athena/request_feedback_suggestions.ts
> +    retry: 3,
Why do we need this?

2023-11-08 19:37 UTC, pal03377 requested changes
I get no automatic evaluation and no feedback about this at all when trying it on the test server :(

![Uploading screenshot-2023-11-08_002086.png…]()

2023-11-08 19:38 UTC, pal03377 commented
Also, the `automatic_evaluation` file did not contain the `LLM-as-a-judge`, `llm_statistics`, and `feedback_statistics` keys

2023-11-09 09:49 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/utils.py
> +def get_line_range_from_index_range(index_start: Optional[int], index_end: Optional[int], content: str) -> Tuple[Optional[int], Optional[int]]:
It is rather module specific I think, but generally could see it also being part of the Athena package. I would not move it now because in `get_sentence_spans` I'm using `nltk`'s sentence tokenization which I need to download in `__main__`:
```
if __name__ == "__main__":
    nltk.download("punkt")`
```

2023-11-09 09:57 UTC, FelixTJDietrich commented on playground/src/hooks/athena/request_feedback_suggestions.ts
> +    retry: 3,
Locally I did not need this, but when I sent feedback for more than `50` training submissions in the evaluation mode on the test server I did get stuck some time. With this it works with `500` training submissions without fail, if it still fails you need to export -> cancel -> import to recover for now.

But you have a point. I'm also using this in "Module Requests" and there we should not retry

2023-11-09 10:05 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/evaluation.py
> +        suggestions_with_grading_instructions)
Yeah, I'm no longer misusing `suggestions_with_grading_instructions` as `unmatched_ suggestions_with_grading_instructions` now and can use `len(` now below

2023-11-09 10:05 UTC, FelixTJDietrich commented on playground/src/hooks/athena/request_feedback_suggestions.ts
> +    retry: 3,
Moved it to the evaluation mode hook 👍

2023-11-09 10:33 UTC, FelixTJDietrich commented
Seems like I did not validate the `structured_grading_instruction_id`, it should be fine now.

2023-11-09 10:40 UTC, FelixTJDietrich commented
Works for me on the test server now :)
<img width="646" alt="image" src="https://github.com/ls1intum/Athena/assets/5898705/c9c9389d-1f57-4217-8b85-8e5d95a5ece4">
<img width="812" alt="image" src="https://github.com/ls1intum/Athena/assets/5898705/5668b3cb-30f4-45b1-a5c3-b8e3964f65ae">

2023-11-11 11:30 UTC, FelixTJDietrich commented
I also added now some docs:
<img width="532" alt="image" src="https://github.com/ls1intum/Athena/assets/5898705/7fca360a-8350-4c33-a2f6-d7266bad2ced">

2023-11-12 20:58 UTC, pal03377 approved these changes
The exported files look like expected. I also cannot find any issues (neither in the code nor in my tests) ✅

2023-11-12 22:35 UTC, merged