Feature/modelling exercise feedback
pal03377/Athena-New pull request #196
Opened 2024-01-01 22:45 UTC by matthiaslehnertum

### Motivation and Context

### Description

### Steps for Testing

### Screenshots

2024-01-26 13:25 UTC, maximiliansoelch requested changes

2024-01-26 13:25 UTC, maximiliansoelch commented on playground/src/model/feedback.ts
> +  type: "modelling";
Shouldn't there be some kind of reference to the model element the feedback is assigned to?

2024-01-26 13:25 UTC, maximiliansoelch commented on module_modelling_llm/README.md
> +# Module Text LLM
This should be adapted for the modeling module

2024-01-26 13:25 UTC, maximiliansoelch commented on module_modelling_llm/Dockerfile
> +# This is the Dockerfile for the assessment module manager.
Copy&Paste error

2024-01-26 13:25 UTC, maximiliansoelch commented on assessment_module_manager/modules.docker.ini
> +supports_evaluation = false
Shouldn't this be true? 🤔
```suggestion
supports_evaluation = true
```

2024-01-26 13:25 UTC, maximiliansoelch commented on assessment_module_manager/modules.ini
> +supports_evaluation = false
Same as above:
```suggestion
supports_evaluation = true
```

2024-01-26 13:25 UTC, maximiliansoelch commented on module_modelling_llm/module_modelling_llm/helpers/models/replicate.py
Do we already need this file?

2024-02-03 12:55 UTC, marlon-luca-bu approved these changes
Code looks good to me 👍

2024-02-07 17:59 UTC, maximiliansoelch approved these changes
Changes look good, thanks for the contribution 👍

2024-02-07 17:59 UTC, merged