Introduce support for multiple Artemis Instances
pal03377/Athena-New pull request #279
Opened 2024-05-19 19:25 UTC by undernagruzez

### Motivation and Context

Right now one Athena deployment supports only one Artemis deployment. In the future, one Athena deployment should support multiple test servers or production servers. This requires changes in the db schema and authentication. Also, Playground has to be adjusted, but this will be done here: https://github.com/ls1intum/Athena/pull/284

### Description

I reworked the concept of authentication and introduced support for multiple Artemis instances. 
1. In the Assessment module manager there is a file: deployment.ini. It enumerates supported Artemis deployments. For each deployment there should be a corresponding key.
2. I slightly improved the differentiation between module API secrets and Artemis API secrets in code.
3. I introduced a new column in the database for each column: lms_url and added a new unique constraint: for id and lms_url.
4. I added a new request HTTP header: X-Server-Url, that will be used to check the authentication key in the authentication middleware.

### Steps for Testing
Make sure the corresponding Artemis PR is deployed: https://github.com/ls1intum/Artemis/pull/8635.
Deploy this PR using github actions, deploy the Artemis PR to any test server and use an arbitrary feature requiring Athena. Make sure everything works.

2024-06-07 21:32 UTC, maximiliansoelch requested changes
Please double-check that we stay LMS unspecific in the code

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/authenticate.py
> +def verify_artemis_athena_key(lms_url: str, secret: str):
```suggestion
def verify_lms_athena_key(lms_url: str, secret: str):
```

2024-06-07 21:32 UTC, maximiliansoelch commented on athena/athena/contextvars.py
> +def get_artemis_url():
```suggestion
def get_lms_url():
```

2024-06-07 21:32 UTC, maximiliansoelch commented on athena/athena/contextvars.py
> +def set_artemis_url_context_var(lms_url: str):
```suggestion
def set_lms_url_context_var(lms_url: str):
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        # should be the same as the Artemis key
```suggestion
        # should be the same as the LMS key
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/env.py
> +    secret = os.environ.get(f"ARTEMIS_{deployment.name.upper()}_SECRET")
```suggestion
    secret = os.environ.get(f"LMS_{deployment.name.upper()}_SECRET")
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/env.py
> +        logger.warning("Missing secret for Artemis deployment %s. "
```suggestion
        logger.warning("Missing secret for LMS deployment %s. "
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/env.py
> +                       "Set the ARTEMIS_%s_SECRET environment variable to secure the communication "
```suggestion
                       "Set the LMS_%s_SECRET environment variable to secure the communication "
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/endpoints/modules_proxy_endpoint.py
> +    artemis_server_url = request.headers.get('X-Server-URL')
```suggestion
    lms_server_url = request.headers.get('X-Server-URL')
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/endpoints/modules_proxy_endpoint.py
> +    if artemis_server_url:
```suggestion
    if lms_server_url:
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/endpoints/modules_proxy_endpoint.py
> +        headers['X-Server-URL'] = artemis_server_url
```suggestion
        headers['X-Server-URL'] = lms_server_url
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/endpoints/modules_proxy_endpoint.py
> +        artemis_server_url,
```suggestion
        lms_server_url,
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/deployment/list_deployments.py
> +    """Get a list of all Artemis instances that Athena should support."""
```suggestion
    """Get a list of all LMS instances that Athena should support."""
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/deployment/deployment.py
> +    """An Artemis instance, with the URL and keys."""
```suggestion
    """An LMS instance, with the URL and name."""
```

2024-06-07 21:32 UTC, maximiliansoelch commented on assessment_module_manager/assessment_module_manager/authenticate.py
> +        raise HTTPException(status_code=401, detail="Invalid Artemis Server Url.")
```suggestion
        raise HTTPException(status_code=401, detail="Invalid X-Server-URL.")
```

2024-06-09 12:39 UTC, FelixTJDietrich commented
The Playground does not work with this out of the box I believe. The local dev environment should always just work out of the box IMO.

2024-06-09 12:57 UTC, FelixTJDietrich requested changes

2024-06-09 12:57 UTC, FelixTJDietrich commented on assessment_module_manager/deployments.ini
How to use the playground without always changing this?

2024-06-09 12:59 UTC, FelixTJDietrich commented on assessment_module_manager/deployments.ini
This should probably be port `3000`
The playground is our local "LMS"!

2024-06-09 15:38 UTC, undernagruzez commented on assessment_module_manager/deployments.ini
> How to use the playground without always changing this?

has been added here: https://github.com/ls1intum/Athena/pull/284

2024-06-09 16:01 UTC, undernagruzez commented
The deployment is currently broken. I deployed this PR manually and created an issue for the deployment script, as fixing the deployment here would create unnecessary overhead(https://github.com/ls1intum/Athena/issues/294).

2024-06-09 16:33 UTC, FelixTJDietrich commented on assessment_module_manager/deployments.ini
Alright :)

2024-06-09 16:42 UTC, FelixTJDietrich commented
@undernagruzez I appreciate this change but it is hard for me to follow, I kind of understand them now 😄 I know you talked a lot about this with @maximiliansoelch but other devs also need to understand what is going on, at least now that we have more people working on Athena again.

Can you detail the motivation behind the changes and describe your solution in more detail? From the PR description alone I can't deduct it :/

2024-06-11 11:14 UTC, marlon-luca-bu commented
> @undernagruzez I appreciate this change but it is hard for me to follow, I kind of understand them now 😄 I know you talked a lot about this with @maximiliansoelch but other devs also need to understand what is going on, at least now that we have more people working on Athena again.
> 
> Can you detail the motivation behind the changes and describe your solution in more detail? From the PR description alone I can't deduct it :/

Same for me actually, could you extend the description and your solution a bit more? :)

2024-07-10 14:21 UTC, FelixTJDietrich commented on assessment_module_manager/assessment_module_manager/env.py
> +DEPLOYMENT_SECRETS = {}
I think it would make more sense to reverse keys and values, so not the url as key but the name. Then you have a lookup table from url to name and also store the name in the database 🤔 I think always storing the url with each entry seems a bit off to me, but I mean it works

2024-07-10 14:21 UTC, FelixTJDietrich commented on athena/athena/endpoints.py
> +            isGraded: is_graded_type = Body(True, alias="isGraded"),
is the alias for `isGraded` necessary?

2024-07-10 14:21 UTC, FelixTJDietrich commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
This could be the deployment name, IMO

2024-07-10 14:21 UTC, FelixTJDietrich commented on env_example/assessment_module_manager.env
> +ARTEMIS_DEPLOYMENT_NAME_SECRET=12345abcdef
I think here it should also be LMS? instead of Artemis?

2024-07-15 05:12 UTC, undernagruzez commented on assessment_module_manager/assessment_module_manager/env.py
> +DEPLOYMENT_SECRETS = {}
Max and I decided to use the URLs, which can be uniquely utilized and immediately seen. Additionally, names would lead to an increase in the configuration. But we can discuss this point again.

2024-07-15 05:12 UTC, undernagruzez commented on athena/athena/endpoints.py
> +            isGraded: is_graded_type = Body(True, alias="isGraded"),
Yes, because the property is called isGraded in te dto.

2024-07-15 05:13 UTC, undernagruzez commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
I think it was Max's wish to have it as an lms URL.

2024-07-15 05:13 UTC, undernagruzez commented on env_example/assessment_module_manager.env
> +ARTEMIS_DEPLOYMENT_NAME_SECRET=12345abcdef
Yes, you are right.

2024-07-15 08:31 UTC, FelixTJDietrich approved these changes
LGTM

2024-07-15 13:28 UTC, FelixTJDietrich commented
@maximiliansoelch can be merged IMO

2024-07-15 13:30 UTC, FelixTJDietrich commented
I think I will just merge it :)

2024-07-15 15:00 UTC, merged