Fix function calling, more verbose logging, OpenAI upgrade
pal03377/Athena-New pull request #280
Opened 2024-05-20 11:27 UTC by undernagruzez

### Motivation and Context
Langchain release a new major upgrade. The version in module programming llm was far behind and had to be upgraded. This PR addresses this and also adds a bit better logging.

### Description

What was changed:
1. The way llm chains are built - was updated to use the new features of langchain.
2. The way LLM models are initialized - because of stuff removed from the long chain.
3. A flag to support more verbose logging.
4. Repeated LLM invocations - in case of failures, additional invocations will be issued, up to 3 times.

### Steps for Testing

Just deploy it to the test server and request feedback and suggestions from Athena and Artemis.

2024-07-26 09:34 UTC, FelixTJDietrich commented
What is up with this PR? Can you update it? Also the PR description is missing. 

If it is not ready can you please put it in draft until it is ready. Also try to find reviewers for the PR once it is ready.

2024-07-26 09:44 UTC, undernagruzez commented
> What is up with this PR? Can you update it? Also the PR description is missing.
> 
> If it is not ready can you please put it in draft until it is ready. Also try to find reviewers for the PR once it is ready.

This PR is ready to review. I updated the description.

2024-07-26 11:07 UTC, FelixTJDietrich commented on module_programming_llm/module_programming_llm/helpers/models/openai.py
> +                # if deployment.capabilities["completion"]:
Remove commented out code?

2024-07-26 11:09 UTC, FelixTJDietrich commented on module_programming_llm/module_programming_llm/helpers/models/openai.py
> +available_models = _get_available_models(available_deployments)
We are only supporting models that are deployed on Azure OpenAI? What about OpenAI models that are not deployed on Azure? We also want to be able to use them

2024-07-26 11:13 UTC, FelixTJDietrich requested changes

2024-07-26 11:13 UTC, FelixTJDietrich commented on athena/athena/models/model.py
> +from pydantic import BaseModel, AnyUrl
There are some unused imports

2024-07-26 11:41 UTC, FelixTJDietrich commented
On the test server the programming LLM and the text LLM modules are not working.

2024-10-04 02:21 UTC, closed without merging

2024-10-04 02:22 UTC, undernagruzez commented
Handled here: https://github.com/ls1intum/Athena/pull/342