Upgrade Playground
pal03377/Athena-New pull request #284
Opened 2024-06-03 09:00 UTC by undernagruzez

### Motivation and Context
Playground was not extended to support self-learning feedback generation, although this feature exists.
Also, this PR https://github.com/ls1intum/Athena/pull/280 changed some internals and changed Authentication.
Playground was not affected. This PR fixes that.

### Description
1. Renamed all URL fields into uri fields to stay consistent with Artemis.
2. Added deployment information about Playground to enable support for new Authentication.
3. Updated nodejs version for docker images.
4. Added lms(client) URL field to the playground header.
5. Chaned athena fetcher to modify the authorization headers in Playground client.
6. Chaned Playground server to forward these headers.
7. Removed unnecessary yarn lock file.
### Steps for Testing
Deploy the testing setup on the ts or locally. Submit new self-learning-feedback requests and old graded requests. Verify everything works.
For local, the key is empty. For athena ts3, the key is here: https://confluence.ase.in.tum.de/pages/viewpage.action?pageId=25252245

### Screenshots
![image](https://github.com/ls1intum/Athena/assets/33299157/332c496d-7abc-4149-bd84-2724e9e36d36)

2024-06-06 08:16 UTC, FelixTJDietrich commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
Why not use `repository_uri` from `programming_submission.py`?

2024-06-06 17:21 UTC, undernagruzez commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
repository urls can differ: we can use gitlab, local vc etc

2024-06-06 20:48 UTC, FelixTJDietrich commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
Why can‘t you just send the correct url to Athena then?

2024-06-06 20:59 UTC, undernagruzez commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
It will be sent: https://github.com/ls1intum/Artemis/pull/8635
Or what do you mean?

2024-06-06 21:10 UTC, FelixTJDietrich commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
But why? Why set it in the header?
Aetemis sends the programming submission containing a repository_url (or uri idk). Why is the server not set there?

2024-06-09 15:40 UTC, undernagruzez commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
> But why? Why set it in the header?
> Artemis sends the programming submission containing a repository_url (or uri idk). Why is the server not set there?

I’m not sure I understand your suggestion. Are you proposing to set the LMS URL in the DTOs sent by the LMS, instead of setting it in the headers? If you mean extracting the LMS URL from the programming exercise properties, that won’t work, as we cannot extract this data for text and modeling exercises.

2024-06-09 16:31 UTC, FelixTJDietrich commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
I guess I get it now 🤔 
Paul and me just assumed that we have one secret for the whole Athena server. But I guess your problem is more that you'd have submission ids of different LMSs colliding etc.

2024-06-09 17:41 UTC, undernagruzez commented on athena/athena/models/model.py
> +    lms_url = Column(String, index=True, nullable=False)
Yes exactly, since we plan to use this only testserver(and potentially the prod servers) with multiple Artemis instances, we need this change, but it comes from another PR, and this is just a stacked PR.

2024-06-23 16:04 UTC, DominikRemo requested changes
Tested locally and on ts. I found that I get the error **Failed to get config options from Athena**, which I do not get on develop. So I couldn't really test it.
<img width="498" alt="Bildschirmfoto 2024-06-23 um 18 03 48" src="https://github.com/ls1intum/Athena/assets/47261058/8ad8bf75-9de7-458b-9237-e36fbe07b97d">

2024-06-23 17:15 UTC, FelixTJDietrich commented
@DominikRemo you probably did not use the Athena Testserver Secret from confluence

2024-06-24 11:23 UTC, undernagruzez commented
@FelixTJDietrich @DominikRemo there was actually an issue with the dockerfile, it didn't want to move a file in the container...

2024-06-24 12:23 UTC, DominikRemo requested changes
I no longer get the same error message from before, but now I get another error message:
<img width="498" alt="Bildschirmfoto 2024-06-24 um 14 16 16" src="https://github.com/ls1intum/Athena/assets/47261058/4182c20a-6214-4301-999b-43446cb5433a">
I tried with the Module Requests mode.
Chose the Module _module_text_cofee_
And then tried to send submissions (does not matter what exercise)
It still works on develop, but not on this branch. Do I need to configure something differently or is it a fault on your site?

2024-06-24 12:26 UTC, undernagruzez commented
> I no longer get the same error message from before, but now I get another error message: <img alt="Bildschirmfoto 2024-06-24 um 14 16 16" width="498" src="https://private-user-images.githubusercontent.com/47261058/342332896-4182c20a-6214-4301-999b-43446cb5433a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzIxNTUsIm5iZiI6MTcxOTIzMTg1NSwicGF0aCI6Ii80NzI2MTA1OC8zNDIzMzI4OTYtNDE4MmMyMGEtNjIxNC00MzAxLTk5OWItNDM0NDZjYjU0MzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEyMjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMjk1MThiMjczOTc4NmI5NzgwZmZkY2ZhYWU1YjA1ZjgyYzc5NzYzMTQyMmE1NTEyOWIyNTIyYzYzNmI1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DZFMD59DrvmQa5Y3tHchMhtMNVP_HogBMsFqN6mbNYQ"> I tried with the Module Requests mode. Chose the Module _module_text_cofee_ And then tried to send submissions (does not matter what exercise) It still works on develop, but not on this branch. Do I need to configure something differently or is it a fault on your site?

Did you use the key from the confluence page: https://confluence.ase.in.tum.de/pages/viewpage.action?pageId=25252245?
You must set this field: 
<img width="851" alt="image" src="https://github.com/ls1intum/Athena/assets/33299157/29e016ef-f7ec-41bf-96c3-f7b8b3adee12">

2024-06-25 13:38 UTC, DominikRemo approved these changes
I tested it locally.
Anyway, I had another look at it on the test server and it works there. I'll probably need to reconfigure my local setup, but it LGTM on test server

2024-07-02 19:36 UTC, DominikRemo submitted a review, later dismissed
Tested locally and on Athena ts3.

Tested graded and non graded feedback for programming_llm and tested text_cofee and text_llm successfully.

Thank you very much for the fixes!

2024-07-02 20:05 UTC, EneaGore approved these changes, later dismissed
Looking good to me in the test server.

2024-07-04 07:07 UTC, laadvo submitted a review, later dismissed
Code looks good and the playground is working on the test server again. Thanks so much for the quick fix! :slightly_smiling_face:

2024-07-15 15:29 UTC, FelixTJDietrich requested changes

2024-07-15 15:29 UTC, FelixTJDietrich commented on assessment_module_manager/deployments.docker.ini
> +url = https://ma-schwind.ase.cit.tum.de
Is this correct? I tried to resolve the conflicts

2024-07-15 15:29 UTC, FelixTJDietrich commented on assessment_module_manager/deployments.ini
> +url = http://localhost:8080
Is this correct? I tried to resolve the conflicts

2024-07-15 15:29 UTC, FelixTJDietrich commented on assessment_module_manager/assessment_module_manager/endpoints/health_endpoint.py
> +                    "supportsNonGradedFeedbackRequests": True
I think we would also want to have:
`supportsGradedFeedbackRequests`

2024-07-15 15:29 UTC, FelixTJDietrich commented on env_example/assessment_module_manager.env
> +LMS_DEPLOYMENT_NAME_SECRET=12345abcdef
I think I accidentally removed a new line

2024-07-15 15:29 UTC, FelixTJDietrich commented on assessment_module_manager/modules.docker.ini
> +supports_non_graded_feedback_requests = false
Can we automatically detect this? :) 
Also for evaluation.

2024-07-15 15:29 UTC, FelixTJDietrich commented on module_modeling_llm/module_modeling_llm/__main__.py
> +async def suggest_feedback(exercise: Exercise, submission: Submission, is_graded: bool, module_config: Configuration) -> List[Feedback]:
I still think it would be cool to have:
`@non_graded_feedback_provider` and `@graded_feedback_provider` as decorators

It would make it clearer, but this is probably out of scope for the PR

2024-07-15 15:29 UTC, FelixTJDietrich commented on playground/src/components/view_mode/evaluation_mode/conduct_experiment/module_experiment_progress.tsx
> +      "generatingGradedFeedbackSuggestions",
I guess we would also have the graded vs non-graded destination for the evaluation mode. Like a checkmark in the beginning and then later you can also only select modules that support it.

2024-07-15 15:29 UTC, FelixTJDietrich commented on playground/src/components/view_mode/module_requests/request_non_graded_feedback_suggestions.tsx
> +          <SubmissionDetail identifier="suggestions" submission={submission} feedbacks={feedbacks} />
Are we rendering non-graded feedback differently? 
As a follow-up issue we could think about if the schema of `NonGradedFeedback` and  `GradedFeedback` should be different 🤔
The `NonGradedFeedback` does not have credits and structured grading instructions and probably needs some other attributes about positivity, priority, etc.

Can you create a follow-up issue for that. This would also then be returned by the `@non_graded_feedback_provider` and `@graded_feedback_provicer` respectively.

2024-07-15 15:29 UTC, FelixTJDietrich commented on playground/src/hooks/batch_module_experiment.ts
> +  const stepGenerateGradedFeedbackSuggestions = async () => {
Can you also make it work for non-graded feedback? :) 

But I think we have to do this more as a follow-up issue. Can you create it? I.e. `Adjust evaluation mode to support non-graded feedback`. This would also include displaying it correctly

2024-07-26 08:42 UTC, undernagruzez commented on playground/src/hooks/batch_module_experiment.ts
> +  const stepGenerateGradedFeedbackSuggestions = async () => {
I created an issue: https://github.com/ls1intum/Athena/issues/317

2024-07-26 08:47 UTC, undernagruzez commented on playground/src/components/view_mode/module_requests/request_non_graded_feedback_suggestions.tsx
> +          <SubmissionDetail identifier="suggestions" submission={submission} feedbacks={feedbacks} />
I will create an issue, but we use the same schema for Athena modules. We can discuss this in dm or in the Athena meeting.
https://github.com/ls1intum/Athena/issues/318

2024-07-26 08:47 UTC, undernagruzez commented on playground/src/components/view_mode/evaluation_mode/conduct_experiment/module_experiment_progress.tsx
> +      "generatingGradedFeedbackSuggestions",
For a follow-up that extends the evaluation mode?

2024-07-26 08:48 UTC, undernagruzez commented on assessment_module_manager/deployments.docker.ini
> +url = https://ma-schwind.ase.cit.tum.de
Should be correct.

2024-07-26 08:49 UTC, undernagruzez commented on assessment_module_manager/deployments.ini
> +url = http://localhost:8080
same

2024-07-26 08:50 UTC, undernagruzez commented on assessment_module_manager/assessment_module_manager/endpoints/health_endpoint.py
> +                    "supportsNonGradedFeedbackRequests": True
I thought all modules should have graded feedback suggestions by default. If that is not the case, I can quickly modify this part.

2024-07-26 08:52 UTC, undernagruzez commented on assessment_module_manager/modules.docker.ini
> +supports_non_graded_feedback_requests = false
See the answer below.

2024-07-26 08:53 UTC, undernagruzez commented on module_modeling_llm/module_modeling_llm/__main__.py
> +async def suggest_feedback(exercise: Exercise, submission: Submission, is_graded: bool, module_config: Configuration) -> List[Feedback]:
We might decide to use different decorators. Then, we could scan over the main.py and see if the corresponding decorator is within the file to automatically set the flags.

2024-07-26 09:11 UTC, FelixTJDietrich commented on assessment_module_manager/assessment_module_manager/endpoints/health_endpoint.py
> +                    "supportsNonGradedFeedbackRequests": True
Could be optional in my opinion. Maybe there is a module that works really well only for preliminary feedback but does not make sense for graded feedback 🤔

2024-07-26 09:14 UTC, FelixTJDietrich commented on playground/src/components/view_mode/evaluation_mode/conduct_experiment/module_experiment_progress.tsx
> +      "generatingGradedFeedbackSuggestions",
Do it in a follow-up. I think the evaluation mode still works without problems but only for the graded feedback suggestions.

2024-07-26 09:28 UTC, FelixTJDietrich commented
Why is the prospector linting check failing? Can we fix this in a follow-up, I will create an issue.
```
Run echo "$HOME/.local/bin" >> $GITHUB_PATH
Creating virtualenv athena-modularized-tH5MAedG-py3.11 in /home/runner/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
```

2024-07-26 09:30 UTC, FelixTJDietrich approved these changes
Code LGTM, works as expected on the test server. I will merge it now.

2024-07-26 09:30 UTC, merged

2024-07-26 09:38 UTC, undernagruzez commented
> Why is the prospector linting check failing? Can we fix this in a follow-up, I will create an issue.
> 
> ```
> Run echo "$HOME/.local/bin" >> $GITHUB_PATH
> Creating virtualenv athena-modularized-tH5MAedG-py3.11 in /home/runner/.cache/pypoetry/virtualenvs
> Installing dependencies from lock file
> 
> pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
> ```

This is because we use different versions of langchain for different llm modules. We cannot fix it now but this issue will disappear when we decouple modules from the top-level module(I will create a PR by tomorrow).