ThemisML Module
pal03377/Athena-New pull request #30
Opened 2023-06-11 13:17 UTC by pal03377

This PR introduces a new ThemisML module based on https://github.com/ls1intum/Themis-ML

Currently, it's IMO not fast enough for production usage, but the suggestion algorithm already works for whole methods.

To test: 
- Send submissions of the "Hello World" exercise
- Send feedback of the "Hello World" exercise
- Request feedback suggestions for the submission with ID 104, which references the same code as submission 101 with feedback (a bit simplistic, I know - but works for basic testing)
- You should get back a suggestion:
<img width="715" alt="screenshot-2023-06-11_001427" src="https://github.com/pal03377/Athena-New/assets/9006596/50efb05b-73cc-4f2e-9d51-e6b6e1960e9f">

I also changed the feedback schemas and models in a way that could already solve #22 in the process (closes #22)

2023-06-29 12:59 UTC, FelixTJDietrich commented
On send feedback of submission `101` and feedback `101` I get:
Code `422`
```
{
  "module_name": "module_programming_themisml",
  "status": 422,
  "data": {
    "detail": [
      {
        "loc": [
          "body",
          "feedback",
          "exercise_id"
        ],
        "msg": "field required",
        "type": "value_error.missing"
      },
      {
        "loc": [
          "body",
          "feedback",
          "submission_id"
        ],
        "msg": "field required",
        "type": "value_error.missing"
      },
      {
        "loc": [
          "body",
          "feedback",
          "detail_text"
        ],
        "msg": "field required",
        "type": "value_error.missing"
      },
      {
        "loc": [
          "body",
          "feedback",
          "text"
        ],
        "msg": "field required",
        "type": "value_error.missing"
      },
      {
        "loc": [
          "body",
          "feedback",
          "credits"
        ],
        "msg": "field required",
        "type": "value_error.missing"
      },
      {
        "loc": [
          "body",
          "feedback",
          "meta"
        ],
        "msg": "field required",
        "type": "value_error.missing"
      }
    ]
  }
}
```

2023-06-29 13:55 UTC, FelixTJDietrich requested changes
Some feedback already on everything except themis ^^ Will continue looking at it.

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/models/db_programming_feedback.py
> +    line_end: int = Column(Integer)  # type: ignore
I think the type for all three should be `Optional[...]`

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/feedback.py
> +            meta: dict = None,  # type: ignore # This is None to avoid mutable default arguments
Wouldn't `Optional[dict]` still make sense? You are removing the optional with `or {}` below

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/models/db_programming_feedback.py
> +    def get_code(self):
Maybe add a return type and mention in the method description that it can throw a `ValueError`. Maybe it is also a bit confusing, maybe call it `get_referenced_code`? Also, I don't know if we allow it but if we have only `file_path` set without `line_start` and `line_end`, I would assume that it gives me the code for the whole file.

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/models/db_programming_exercise.py
> +    tests_repository_url: str = Column(String)  # type: ignore
I'm a bit confused by the `nullable` in `sqlalchemy`, I think by default everythin is nullable now? Shouldn't we then have `nullable=False` for most db columns? At least here

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/programming_feedback.py
> +    line_end: Optional[int] = Field(None, example=2)
Maybe we can have a more safer type for this. For example right now I could set only `line_end` to `None`, but `line_start` and `line_end` should only be settable when `file_path` is set and then both have to be not `None`.

I guess you mention below that single line feedback is when `line_end` is `None` 🤔, but maybe that is also confusing.

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/programming_feedback.py
> +            raise ValueError("Feedback does not have a line start")
Maybe mention that it throws an `ValueError` in the docstring or think about changing the return type.

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/programming_submission.py
> +        Might be quite an expensive operation! If you need to fetch multiple files, consider using get_zip() instead.
I guess some kind of caching would be nice, but we can do it as a follow up issue and discuss how we should handle the repository downloads in general.

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/programming_submission.py
> +        Might be quite an expensive operation! If you need to fetch multiple files, consider using get_zip() instead.
Alternativly, there is already some caching in `get_repository`. You can use that and then return the file's content from there.

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/programming_submission.py
> +    def get_code(self, file_path: str):
A return type would be nice

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/text_feedback.py
> +    index_end: Optional[int] = Field(description="The end index of the feedback in the submission text.", example=10)
Here we could also have a safer type, at least for the schema class, I think for the db it is fine. What do you think?

2023-06-29 13:55 UTC, FelixTJDietrich commented on athena/athena/schemas/text_feedback.py
> +            meta: dict = None,  # type: ignore # This is None to avoid mutable default arguments
Maybe still use `Optional` and do the `or {}` as you did with programming feedback.

2023-06-29 13:55 UTC, FelixTJDietrich commented on module_programming_llm/module_programming_llm/basic/basic_feedback_provider.py
>          if problem_statement is None:
Yeah you are right, sometimes where is an issue and the `file_problem_statements` is not present

2023-06-29 13:55 UTC, FelixTJDietrich commented on module_programming_llm/module_programming_llm/basic/basic_feedback_provider.py
> +        return []
🙏

2023-06-29 13:55 UTC, FelixTJDietrich commented on module_text_cofee/module_text_cofee/models/db_text_block.py
The confusion continues ^^ is `sqlalchemy` now by default nullable or not? I think we have to go over all columns and check this again.

2023-06-29 13:55 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/utils.py
> +def parse_line_number_reference_as_span(reference: str, content: str) -> Tuple[Optional[int], Optional[int]]:
True, I guess I will change it in the future depending how the final prompt reference structure is.

2023-06-29 13:55 UTC, FelixTJDietrich commented on playground/examples/exercise-1/submissions/102/BinarySearch.java
> +        int high = chapters.size() - 1
👍

2023-06-29 13:55 UTC, FelixTJDietrich commented on playground/src/model/feedback.ts
> +  index_end: number;
I guess here we could also use a safer type for the reference structure. Also right now the feedback cannot be unreferenced?

2023-06-29 13:55 UTC, FelixTJDietrich requested changes
Some feedback already on everything except themis ^^ Will continue looking at it.

2023-06-29 14:20 UTC, FelixTJDietrich commented on module_programming_themisml/module_programming_themisml/extract_methods/languages/JavaLexer.py
> +# Generated from JavaLexer.g4 by ANTLR 4.11.1
Did you customize this? If not then it could maybe be a file that can be gitignored and generated on init etc.?

2023-06-29 14:33 UTC, FelixTJDietrich commented
Okay, I looked also at the ThemisML module now and the code looks generally good to me. Though I did not 100% get how it works in detail but I think that is also not too important. I just could not test it because of the error I posted above.

2023-06-29 20:13 UTC, pal03377 reviewed
Fixed the issue you mentioned, let me know if it works now. Also worked on all other feedbacks. Thanks already!

2023-06-29 20:13 UTC, pal03377 commented on playground/src/model/feedback.ts
> +  index_end: number;
I fixed that it now can be unreferenced. What's do you have in mind for the safer type?

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/schemas/programming_feedback.py
> +    line_end: Optional[int] = Field(None, example=2)
I now added pydantic validators to ensure that
- either `line_start` and `line_end` are both None or they are both ints (`line_end` possibly is auto-populated in the validator)
- `line_start` is never larger than `line_end`

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/schemas/programming_feedback.py
> +            raise ValueError("Feedback does not have a line start")
The helper function is now gone in favor of validators

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/schemas/feedback.py
> +            meta: dict = None,  # type: ignore # This is None to avoid mutable default arguments
Resolved by just using pure pydantic models

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/models/db_programming_feedback.py
> +    def get_code(self):
Very valuable feedback! I've implemented it that way 👍

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/models/db_programming_exercise.py
> +    tests_repository_url: str = Column(String)  # type: ignore
I've gone through all models and schemas to solve this for all of them. Now, all not-nullable columns should be marked as such.

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/schemas/programming_submission.py
> +        Might be quite an expensive operation! If you need to fetch multiple files, consider using get_zip() instead.
I suggest to do that as a follow-up

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/schemas/text_feedback.py
> +    index_end: Optional[int] = Field(description="The end index of the feedback in the submission text.", example=10)
I've added two Pydantic validators 👍

2023-06-29 20:13 UTC, pal03377 commented on athena/athena/schemas/text_feedback.py
> +            meta: dict = None,  # type: ignore # This is None to avoid mutable default arguments
outdated now, with pure pydantic schemas

2023-06-29 20:13 UTC, pal03377 commented on module_text_cofee/module_text_cofee/models/db_text_block.py
I did now! 🎉  It's nullable by default

2023-06-29 20:13 UTC, pal03377 commented on module_programming_themisml/module_programming_themisml/extract_methods/languages/JavaLexer.py
> +# Generated from JavaLexer.g4 by ANTLR 4.11.1
I thought of this, but then I would have to download the grammar files from https://github.com/antlr/grammars-v4/tree/master/java/java and compile them. This would be an extra setup step for local developers, which wouldn't bring that much value, on the other hand. What do you think? I'm still a bit unsure

2023-07-03 08:14 UTC, FelixTJDietrich commented on playground/src/model/feedback.ts
> +  index_end: number;
Nevermind let's just leave it like this. There seems to not be a good way to have an enum with associated values.

I thought about something like this Swift code (for programming exercises):
```
enum FeedbackType {
    case unreferenced
    case unreferencedFile(filePath: String)
    case referenced(filePath: String, lineRange: (start: Int, end: Int))
}
```

2023-07-03 08:15 UTC, FelixTJDietrich commented on module_programming_themisml/module_programming_themisml/extract_methods/languages/JavaLexer.py
> +# Generated from JavaLexer.g4 by ANTLR 4.11.1
Yeah, I think it makes sense to commit it now. It just makes it harder to get started.

2023-07-03 08:23 UTC, FelixTJDietrich approved these changes
Code LGTM :)
I also tested it now with the playground and it runs for me at least. I could not find submission 104 in my dropdown but at least it responded successfully

2023-07-04 00:47 UTC, merged