Feature/create module programming winnowing
pal03377/Athena-New pull request #315
Opened 2024-07-19 10:43 UTC by marlon-luca-bu

### Motivation and Context

This PR introduces a new module winnowing.

### Description

Added new module winnowing

### Steps for Testing

Start Athena and verify it is working

### Screenshots

2024-11-18 10:18 UTC, maximiliansoelch requested changes
Please use only the resources from the winnowing module to avoid the dependencies to the apted module. Also get rid of the added init.py files where they are not required.

2024-11-18 10:18 UTC, maximiliansoelch commented on athena/pyproject.toml
> +pydantic = "1.10.13"
This change conflicts with the pydantic dependency already present in the dev-dependencies. Therefore also the linting and testing fails.

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/__init__.py
Is this file needed? Otherwise I wouldn't want to add it here.

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/programming/__init__.py
Is this file needed? Otherwise I wouldn't want to add it here.

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/programming/module_programming_winnowing/module_programming_winnowing/test_codes/__init__.py
Is this file needed? Otherwise I wouldn't want to add it here.

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/programming/module_programming_winnowing/pyproject.toml
> +athena = {path = "../athena", develop = true}
This needs to be adapted to the new project structure:
```suggestion
athena = { path = "../../../athena", develop = true }
```

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/programming/module_programming_winnowing/pyproject.toml
> +module_programming_apted = {path = "../module_programming_apted", develop = true}
```suggestion
```

Why do we need the dependency on your other module? You added the ANTLR generated files in this module anyways, so I suggest to just use them.

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/programming/module_programming_winnowing/module_programming_winnowing/convert_code_to_ast/languages/java/JavaParser.py
Is it intended that the generated JavaParser is different than the one in the apt module?

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/programming/module_programming_winnowing/Dockerfile
> +COPY --from=module_programming_apted /code /module_programming_apted
This shouldn't be there 
```suggestion
```

2024-11-18 10:18 UTC, maximiliansoelch commented on modules/programming/module_programming_winnowing/module_programming_winnowing/convert_code_to_ast/extract_method_and_ast.py
> +from module_programming_apted.convert_code_to_ast.languages.python.Python3Lexer import Python3Lexer
This should use the Lexer in the winnowing module instead of the one from the apted module. Also please update it in all other correlating files

2024-11-30 12:55 UTC, marlon-luca-bu commented on modules/programming/module_programming_winnowing/pyproject.toml
> +module_programming_apted = {path = "../module_programming_apted", develop = true}
Actually I dont know anymore, why this was here. I guess for testing purposes - deleted it

2024-11-30 12:57 UTC, marlon-luca-bu commented on modules/programming/module_programming_winnowing/Dockerfile
> +COPY --from=module_programming_apted /code /module_programming_apted
I saw that @dmytropolityka added this line here ... can you remember why? @dmytropolityka

2024-11-30 13:16 UTC, marlon-luca-bu commented on modules/__init__.py
Short googeling, why this file can be important, so I would just keep them:

_Ein __init__.py-File ist in Python-Projekten notwendig, um ein Verzeichnis als ein Python-Paket zu kennzeichnen. Dies bedeutet, dass es dem Python-Interpreter ermöglicht, das Verzeichnis als ein Paket zu behandeln und somit Module innerhalb dieses Verzeichnisses zu importieren.

Hier sind einige wichtige Punkte dazu:

Kennzeichnung als Paket : Ohne eine __init__.py-Datei wird ein Verzeichnis nicht als Paket betrachtet und Sie können Module aus diesem Verzeichnis nicht importieren.
Python 3.3 und höher : Seit Python 3.3 ist eine __init__.py-Datei technisch nicht mehr notwendig, um ein Verzeichnis als Paket zu behandeln. Dies liegt daran, dass Python nun auch sogenannte "Namespace-Pakete" unterstützt, die keine __init__.py-Datei benötigen. Trotzdem ist es eine gute Praxis, eine __init__.py-Datei zu verwenden, um Verzeichnisse explizit als Pakete zu kennzeichnen und um Abwärtskompatibilität mit älteren Python-Versionen zu gewährleisten.
Inhalt der __init__.py-Datei : Die __init__.py-Datei kann leer sein, sie kann aber auch Initialisierungscode enthalten, der beim Import des Pakets ausgeführt wird. Dies kann nützlich sein, um bestimmte Einstellungen vorzunehmen oder um Submodule automatisch zu importieren.
Zusammenfassend ist eine __init__.py-Datei nicht immer technisch notwendig, aber es ist eine bewährte Praxis, sie zu verwenden, um die Struktur und das Verhalten Ihres Projekts klar und konsistent zu gestalten._

2024-11-30 15:07 UTC, marlon-luca-bu commented on modules/programming/module_programming_winnowing/module_programming_winnowing/convert_code_to_ast/languages/java/JavaParser.py
As far as I remember this is because of the different way the winnowing algorithm works

2024-12-05 10:45 UTC, merged