Fix: replace snake case file names with camelCase
pal03377/Athena-New pull request #316
Opened 2024-07-20 04:30 UTC by Abhinav-Chdhary

### Motivation and Context

Fixes #68 replacing snake_case with camelCase, for consistency.

### Description

Renamed files and imports that were using snake_case

### Steps for Testing

Switch to replaceSnakeCaseWithCamel branch and try npm run dev

### Screenshots

No change in UI

2024-07-22 06:12 UTC, Abhinav-Chdhary commented
Hi @undernagruzez can you help me understand why these checks failed?

2024-07-22 08:04 UTC, undernagruzez commented
I suppose the error is related to the origin of the branch, but will check once again later

2024-08-05 19:58 UTC, FelixTJDietrich commented
Code looks good to me, I merged some code on the playground and this would need to be updated. But this can generally be merged once tested on the test server.

2024-08-06 03:13 UTC, Abhinav-Chdhary commented
> Code looks good to me, I merged some code on the playground and this would need to be updated. But this can generally be merged once tested on the test server.

And how can we do that?

2024-08-06 06:13 UTC, FelixTJDietrich requested changes
You'd need to resolve the conflicts, I don't think I can resolve them in the fork.

2024-08-06 06:13 UTC, FelixTJDietrich commented on playground/scripts/artemis/1LoadAnonymizedDatabase_dump.mjs
Can you also do `1-LoadAnonymizedDatabaseDump`? I think it looks weird otherwise. We also mention the scripts in the docs and they'd need to be updated.

2024-08-06 06:31 UTC, Abhinav-Chdhary commented on playground/scripts/artemis/1LoadAnonymizedDatabase_dump.mjs
Okay I'll try fixing this .

2024-08-07 06:52 UTC, FelixTJDietrich commented
It looks like this for me, can you pull from develop and resolve the conflicts?
![image](https://github.com/user-attachments/assets/81c96837-3412-4f72-9246-4602d122de4f)

2024-08-07 08:31 UTC, Abhinav-Chdhary commented
> It looks like this for me, can you pull from develop and resolve the conflicts?
Yes I tried that but I got this error. Can you help me understand this?
![image](https://github.com/user-attachments/assets/43d5f6d5-bbe8-4588-8f83-c68573f190f4)

2024-08-07 13:37 UTC, FelixTJDietrich commented
I don't really now 🤔 you renamed a lot of files by changing from `snake_case` to camel `camelCase` and I think git has problems to match it.

2024-08-09 06:56 UTC, Abhinav-Chdhary commented
I'm sorry, I have picked up a new project. I may try this some time later.

2024-08-09 06:56 UTC, closed without merging