`Text_module_llm` Upgrade dependencies and openai model retrieval
pal03377/Athena-New pull request #323
Opened 2024-07-31 17:35 UTC by EneaGore

### Motivation and Context

### Description

### Steps for Testing

### Screenshots

2024-08-01 09:48 UTC, FelixTJDietrich requested changes
Looks good in the playground:
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/0535b73e-c4a5-4a41-a298-7e96a5d0b72b">

Here are some comments. The important part is getting the deployments dynamically. After you're done I can also do a follow-up PR to do some refactoring, I also have some ideas how to can be more maintainable for the future

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/pyproject.toml
> +tiktoken = "^0.7.0"
While you're at it can you remove the carets `^`? I think this would make it more stable for the future.

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/pyproject.toml
> +langchain-openai = "0.1.19"
Why is this not a `0.2` version? Can you group the `langchain` dependencies together?

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +            # kw = model._lc_kwargs
Remove unused comment

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    os.environ["OPENAI_API_VERSION"]=os.environ["LLM_AZURE_OPENAI_API_VERSION"]
Can you update the `.env.example` environment? I thin we are using a newer azure API version. Do you think that it makes sense to set this in the code and not via the environment?

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +############################################################################################
You can remove this part and just directly define the env variables in the environment now:
`AZURE_OPENAI_API_KEY` no longer collides with `OPENAI_API_KEY`. We can remove the prefix :) 🎉

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +actually_deployed_azure= [
Do not hardcode this, use the sdk,  you can have two arrays. `azure_models` and `openai_models` and then you fill them with the available models via the API

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
>      available_deployments: Dict[str, Dict[str, Any]] = {
We can do this in the future when it is necessary. For now we are only interested in the `chat_completions`. Once we need embedding models we can add it then and there but for now let's just focus on the code that is necessary :)

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +def _get_available_deployments():
This should get the available azure deployments from the API

2024-08-01 09:48 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +def _get_available_models(available_deployments: Dict[str, Dict[str, Any]]):
This should get the available non-azure models, maybe you can refactor the code a bit in general so it is clearer. You can change it how you like and don't need to necessarily encapsulate in a function, I did it to hide variables.

2024-08-04 18:02 UTC, EneaGore commented on module_text_llm/pyproject.toml
> +langchain-openai = "0.1.19"
that is the highest atm

2024-08-04 18:03 UTC, EneaGore commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +actually_deployed_azure= [
moved to dependencies, but still using one array for all available models for simplicity

2024-08-04 18:04 UTC, EneaGore commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +def _get_available_deployments():
not possible at the moment to get correct azure deployments from api

2024-08-05 06:36 UTC, FelixTJDietrich requested changes
Good job so far :) 
I will test the functionality soon

2024-08-05 06:36 UTC, FelixTJDietrich commented on module_text_llm/.env.example
> +AZURE_DEPLOYMENTS= '["gpt-35-turbo","gpt-4-turbo","gpt-4-vision","gpt-4o"]'
```suggestion
AZURE_DEPLOYMENTS=gpt-35-turbo,gpt-4-turbo,gpt-4-vision,gpt-4o
```
I think a comma separated list would work better for the env

2024-08-05 06:36 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    for deployment in json.loads(os.environ['AZURE_DEPLOYMENTS']):
```suggestion
    for deployment in os.environ['AZURE_DEPLOYMENTS'].split(','):
```
See comment above

2024-08-05 06:36 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    default_model_name = AZURE_OPENAI_PREFIX+"gpt-35-turbo"
I think the `AZURE_OPENAI_PREFIX` is wrong here. This is about the models hosted via non-azure OpenAI?

2024-08-05 06:36 UTC, FelixTJDietrich commented on module_text_llm/.env.example
> +OPENAI_API_VERSION="2023-07-01-preview" # change base if needed
Is this the current version we are using? Does it need updating?

2024-08-05 06:36 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +import json
Can be removed if we change to `split(',')`

2024-08-05 06:36 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +from langchain_openai import AzureChatOpenAI, AzureOpenAI, ChatOpenAI
Are we even using `AzureOpenAI`? Maybe you have some unused imports.

2024-08-05 09:33 UTC, EneaGore commented on module_text_llm/.env.example
> +OPENAI_API_VERSION="2023-07-01-preview" # change base if needed
These ones are the new names.

2024-08-05 09:34 UTC, EneaGore commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    default_model_name = AZURE_OPENAI_PREFIX+"gpt-35-turbo"
I thought we used the same config for both, at least so it appeared to me.

2024-08-05 10:40 UTC, FelixTJDietrich requested changes

2024-08-05 10:40 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    default_model_name = AZURE_OPENAI_PREFIX+"gpt-35-turbo"
```suggestion
    default_model_name = "gpt-35-turbo"
```
This is just the default model in the case that we have nothing configured as `LLM_DEFAULT_MODEL` for the non-azure case.

2024-08-05 10:41 UTC, FelixTJDietrich commented
Other than the one thing this PR is ready to merge

2024-08-05 14:41 UTC, FelixTJDietrich requested changes

2024-08-05 14:41 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    default_model_name = "gpt-35-turbo"
```suggestion
    default_model_name = None
```

2024-08-05 14:43 UTC, FelixTJDietrich approved these changes
LGTM

2024-08-05 14:43 UTC, merged