More flexible build process for Athena
pal03377/Athena-New pull request #325
Opened 2024-08-04 21:56 UTC by undernagruzez

### Motivation and Context
Athena was initially designed as a modular application with a common module (Athena) that is integral to every other module. With multiple students working asynchronously on different modules, stability issues can arise due to database changes, version upgrades, or feature enhancements. This PR leverages Poetry to enable dynamic importing of the common module, Athena, which eliminates the need for a monolithic structure and enhances modularity.

### Description
1. Each module imports the common Athena module dynamically from either a GitHub repository or a local version.
2. Modules are assembled independently using the provided lint all, lock all, and build all scripts.
3. Developers can specify the required version of the middleware for their module.
4. This PR lays the groundwork for pytest integration.

### Steps for Testing
Deploy the changes to a test server.
Verify that all modules function correctly and that the integration with the common Athena module is stable.

### Resolves
This PR resolves the following issues: https://github.com/ls1intum/Athena/issues/321, https://github.com/ls1intum/Athena/issues/298, https://github.com/ls1intum/Athena/issues/297

2024-08-05 08:03 UTC, FelixTJDietrich commented
Enea currently updated the env files for the text llm module on the test server so that module might not work with this PR right now because of this

2024-08-05 08:14 UTC, FelixTJDietrich commented on install_modules.py
Maybe we can put all those in a scripts folder? I.e. install_modules, lint_modules, lock_modules, test_modules

2024-08-05 08:14 UTC, FelixTJDietrich commented on install_modules.py
> +        "module_modeling_llm",
Max mentioned that you might want to also move the modules in subfolders, in that case you could automatically find them? 

I guess we could have a folder structure like:
modules
 -> text
   -> cofee
   -> llm
 -> programming
   -> themisml
   -> llm
   -> apted
 -> modelling
   -> llm

We can also do this in a follow-up

2024-08-05 08:36 UTC, undernagruzez commented on install_modules.py
> +        "module_modeling_llm",
I will do this in this PR

2024-08-05 08:37 UTC, undernagruzez commented on install_modules.py
Yes, sure

2024-08-08 16:10 UTC, undernagruzez commented on install_modules.py
done

2024-08-08 16:10 UTC, undernagruzez commented on install_modules.py
> +        "module_modeling_llm",
done

2024-08-09 13:02 UTC, FelixTJDietrich commented
Can you also resolve the conflicts?

2024-08-09 13:58 UTC, FelixTJDietrich commented
`module_example` is also a programming module

2024-08-19 14:55 UTC, maximiliansoelch requested changes, later dismissed

2024-08-19 14:55 UTC, maximiliansoelch commented on .idea/runConfigurations/module_programming_llm.xml
I don't think this change should be committed as it includes personal paths

2024-08-19 14:55 UTC, maximiliansoelch commented on .prospector.yaml
Double check why Athena-coffee is not changed

2024-08-19 14:55 UTC, maximiliansoelch commented on modules/text/module_text_cofee/module_text_cofee/.gitignore
Double Check

2024-08-29 10:32 UTC, FelixTJDietrich commented
@undernagruzez ping me on Slack once this is ready, we should merge this ASAP since it causes a lot of merge conflicts

2024-09-02 12:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/pyproject.toml
> +prospector = "^1.10.2"
Why is this no longer a dev dependency?

2024-09-02 12:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/pyproject.toml
> +prospector = "^1.10.2"
Applies to all modules

2024-09-02 12:40 UTC, FelixTJDietrich requested changes
Update `launch.json` and `athena-workspace.code-workspace`

2024-09-04 11:52 UTC, FelixTJDietrich approved these changes
LGTM

2024-09-04 11:56 UTC, FelixTJDietrich commented
Also works on TS1 except for programming llm, idk what's up with that.

2024-09-04 11:56 UTC, merged