Preliminary AI Feedback for all Apollon UML Diagrams
pal03377/Athena-New pull request #335
Opened 2024-09-02 08:10 UTC by LeonWehrhahn

### Motivation and Context

The initial version of the module_modeling_llm was designed to primarily handle BPMN Diagrams. This enhanced implementation uses a new way to parse UML diagrams with a more generic approach making it work with all Apollon supported diagram types. The module has also been updated to utilize Langchain 0.2.15, which allows for the use of native structured output with json_mode for the latest OpenAI models. Additionally, it now supports both graded and non-graded feedback, ensuring that exercise solutions are not revealed when a student requests feedback.

> The module structure is beeing refactoring in a separate PR to enhance maintainability. Including decomposing the generate_suggestions function into smaller, more cohesive units and moving the models into separate files

### Description

1. The new Apollon UML parser converts Apollon JSON into a text representation similar to Mermaid. This representation retains only the most essential attributes of a UML diagram, such as elements, the relationships between them, and the properties/methods associated with these elements and relationships.
2. Since the module was originally built using an older version of Langchain, the code interfacing with Langchain has been rewritten to leverage the new LCE framework. This update also allows for the use of native structured output, eliminating the need to rely on function calling to obtain valid JSON.
3. The module now also differentiates between graded and non-graded feedback. The `is_graded` parameter is set to `true` on the Artemis side when a tutor requests feedback suggestions. When a student requests feedback, `is_graded` is set to `false`. If `is_graded` is `false`, the feedback output is passed through a filter which rewrites the title and descriptions to avoid giving away the solution.
   
   Example: Here we send a student's diagram submission where the start event of a BPMN diagram is missing:

   is_graded = true:
   <img width="803" alt="image" src="https://github.com/user-attachments/assets/66d2c5df-7a53-46b2-a520-7d18f1b38b51">
   is_graded = false:
   <img width="817" alt="image" src="https://github.com/user-attachments/assets/31aabc1d-b0c5-4403-ae3d-eb529b8d2f98">

### Steps for Testing

Option 1: **API Testing:**
   - Make direct API calls to the `/feedback_suggestions` endpoint of the module.
   - Test with various diagram types (BPMN, UML Class, UML Activity, etc.) to ensure the new generic approach works for all Apollon-supported diagrams.
   - For each diagram type, test both `is_graded = true` and `is_graded = false` scenarios.

Option 2. **Athena Playground Testing:**
   - Access the Athena Playground.
   - Use the provided examples to send requests to the Athena `/feedback_suggestions` endpoint.
   - Verify that that appropriate Feedback is returned.

3. **Graded vs. Non-Graded Testing:**
   - For `is_graded = true`:
     - Verify that the feedback provides detailed information including specific solutions.
     - Check that all grading instructions were regarded in the feedback.
   - For `is_graded = false`:
     - Confirm that the feedback does not reveal the solution directly.
     - Ensure that the feedback is helpful but general, guiding the student without giving away answers.

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Athena/athena-test1)](https://athena-test1.ase.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Athena/athena-test2)](https://athena-test2.ase.cit.tum.de)

### Screenshots

2024-09-10 14:54 UTC, undernagruzez requested changes
Reviewed code(excluding UML and Apollon section). Looks good, left a few comments.
What is more important, linting job fails, please update the lock file.

2024-09-10 14:54 UTC, undernagruzez commented on .vscode/launch.json
> +            "cwd": "${workspaceFolder}/module_modeling_llm",
This change is already on develop(see the last object in this json).

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/Dockerfile
> +    && poetry lock --no-update \
Why do you need this command?

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +    if is_graded == False:
Isn't really important, but it would be nice to move this to another file to avoid confusions. But you can also ignore for now.

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/llm_utils.py
> +    chain = RunnableSequence(
Out of curiosity: is this the newest way to write things? I guess I used pipes syntax in module programming llm.

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/llm_utils.py
> +        return await chain.ainvoke(prompt_input, config={"tags": tags})
Do you want to add automatic retries, say 3 times?

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/llm_utils.py
> +        print("OutputParserException or ValidationError", e)
With a corresponding import
```suggestion
        logger.error("Exception type: %s, Message: %s", type(e).__name__, e)
```

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/models/openai.py
> +        models_response = requests.get(f"{base_url}/models?api-version=2023-03-15-preview", headers=headers)
Is this intentional that you want to use this static api version?

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/models/openai.py
> +        deployments_response = requests.get(f"{base_url}/deployments?api-version=2023-03-15-preview", headers=headers)
Same here

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/models/openai.py
> +    OpenAIModel = Enum('OpenAIModel', {name: name for name in available_models}) # type: ignore
What is the reason behind these ignores?

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/models/openai.py
> +    default_openai_model = OpenAIModel[default_model_name] # type: ignore
Here as well

2024-09-10 14:54 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/models/openai.py
> +        model_name: OpenAIModel = Field(default=default_openai_model, # type: ignore
And here

2024-09-11 11:46 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +    if is_graded == False:
Yes, I have a PR in the workings that restructures this module, which also addresses this. See [#340](https://github.com/ls1intum/Athena/pull/340)

2024-09-11 11:48 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/llm_utils.py
> +    chain = RunnableSequence(
Yes, see [LCEL](https://python.langchain.com/v0.1/docs/expression_language/ ) and [structured_output](https://python.langchain.com/v0.2/docs/how_to/structured_output/)

2024-09-11 11:50 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/llm_utils.py
> +        return await chain.ainvoke(prompt_input, config={"tags": tags})
I would address this later. Currently the new json mode seems to work really reliable.

2024-09-11 15:15 UTC, undernagruzez submitted a review, later dismissed

2024-09-11 17:34 UTC, EneaGore submitted a review, later dismissed
code lgtm and it works fine in ts2.

2024-09-11 18:29 UTC, FelixTJDietrich requested changes
Will do more reviewing later

2024-09-11 18:29 UTC, FelixTJDietrich commented on .vscode/launch.json
> +            "justMyCode": false
What does this mean?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/models/openai.py
>  import openai
Did you just copy paste the code from Enea? Then I can skip the review here

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/serializers/parser/uml_parser.py
> +        print("JSON data", json_data)
Remove print statement

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/serializers/parser/element.py
> +class Element:
What is Element? Maybe some documentation would be nice?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/serializers/parser/element.py
> +    def __init__(self, data: Dict[str, Any], element_dict: Optional[Dict[str, Any]] = None):
Would it make sense to use Pydantic for the class?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/serializers/parser/element.py
> +        print(element_dict)
Remove print statement

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/serializers/parser/element.py
> +    def to_apollon(self) -> str:
Can you also add documentation to the methods where it makes sense?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/serializers/parser/relation.py
> +class Relation:
Some documentation on the class and methods would be nice here aswell

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/prompts/apollon_format.py
> +- **ClassDiagram**
Is this used as part of the prompt? Why do you have a general format description instead of per diagram type?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/config.py
> +    graded_feedback_system_message: str = Field(default=default_graded_feedback_system_message,
You can remove the graded naming now

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +    element_names: Optional[List[str]] = Field(description="Referenced diagram element names, and relations (R<number>) or empty if unreferenced")
Are the elements uniquely idenfitied by names?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +    print("Model ", model)
Remove print statements

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +        "submission_format": submission_diagram.get("type"),
I would imagine that you select a prompt for each diagram tyle here instead of passing just the type into a generalized prompt.

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +        "uml_diagram_format": apollon_format_description,
Why have it as variable if it does not change? IMO it should be type specific

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +        print("Filter prompt input", filter_prompt_input)
Search for other print statements, you can also use debug logging etc. if you want to print something

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +            is_graded=False
Why is_graded False?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +            is_graded=False
Shouldn't this also work for the tutor side?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/pyproject.toml
> +langchain-openai = "^0.1.23"
Aren't the dependencies pined to a specific version for the other modules?

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/llm_utils.py
> +    chain = RunnableSequence(
The LCEL way would usually be `chat_prompt | structured_output_llm`

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/prompts/generate_suggestions.py
> +from string import Template
Unused import

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/prompts/generate_suggestions.py
> +filter_feedback_human_message = f"{GRADED_FEEDBACK_OUTPUT}\n\n{OUTPUT_FORMAT}"
IMO the prompts are now harder to reason about. 

You could split the generate feedback prompt and filter feedback prompt into different files and have the system and human messages in just one big multi line string.

2024-09-11 18:29 UTC, FelixTJDietrich commented on modules/modeling/module_modeling_llm/module_modeling_llm/prompts/submission_format/submission_format_remarks.py
> -def get_submission_format_remarks(diagram_type: DiagramType) -> str:
I guess wou would need something similar again for UML diagrams, I would not remove it. 

You can have a generate feedback prompt per uml diagram type and also have them in multiple files. Code duplication with the prompts is fine IMO

2024-09-12 09:18 UTC, LeonWehrhahn commented on .vscode/launch.json
> +            "justMyCode": false
This configures whether during debugging the debugger steps into or skips over non-user code, such as library or framework code. For example when setting breakpoints in library code, these will be ignored if "justMyCode": true

2024-09-12 09:18 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/models/openai.py
>  import openai
Yes, this is the same file content

2024-09-12 10:04 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/prompts/generate_suggestions.py
> +filter_feedback_human_message = f"{GRADED_FEEDBACK_OUTPUT}\n\n{OUTPUT_FORMAT}"
I agree and changed this in another [PR](https://github.com/ls1intum/Athena/pull/340) that restructures the entire module

2024-09-12 10:15 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/helpers/serializers/parser/element.py
> +    def __init__(self, data: Dict[str, Any], element_dict: Optional[Dict[str, Any]] = None):
I don't think that in this context, it makes that much sense to use Pydantic. It would introduce unnecessary overhead and rigidity, as the class doesn't really need the out-of-the-box features Pydantic provides.

2024-09-12 10:17 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +    element_names: Optional[List[str]] = Field(description="Referenced diagram element names, and relations (R<number>) or empty if unreferenced")
Yes, if there are elements with the same name a unique suffix is added.

2024-09-12 10:19 UTC, LeonWehrhahn commented on modules/modeling/module_modeling_llm/module_modeling_llm/generate_suggestions.py
> +        "uml_diagram_format": apollon_format_description,
Yes, doesn't really make sense to have it as a variable here. I suggest that I address this in a follow up PR, as the prompt part is updated in the next restructuring [PR](https://github.com/ls1intum/Athena/pull/340)

2024-09-12 16:30 UTC, FelixTJDietrich requested changes
Please add example data for the diagrams, I could only test BPMN
![image](https://github.com/user-attachments/assets/7d4dba8c-11cc-47b2-95cb-6e941a1008a0)

2024-09-12 18:34 UTC, FelixTJDietrich approved these changes
LGTM

2024-09-12 18:34 UTC, merged