`ModelingLLM`: Add Structured Grading Instruction Generation and Restructure Module
pal03377/Athena-New pull request #340
Opened 2024-09-09 08:06 UTC by LeonWehrhahn

### Motivation and Context

Structured Grading Instructions (SGIs) lead to more accurate feedback generations. However, instructors do not always provide SGIs for every exercise. To address this gap and maintain consistency in the grading process, this PR implements automatic SGI generation when manual ones are not present.

Additionally, as the module has grown with more functions for processing and manipulating data, this PR includes a restructuring to enhance organization and maintainability.

### Description

> A follow-up PR will address caching the structured grading instructions

This PR introduces the following key changes:

1. **Automatic SGI Generation:** Implemented a new function to generate Structured Grading Instructions when they are not manually provided for an exercise.
2. **Module Restructuring:** Reorganized the module structure to better accommodate the growing number of processing and manipulation functions.
3. **Core Functionality Updates:**
    - Restructured generate_suggestions.py to focus solely on the feedback generation process and moved other functionalities into separate functions and files for improved modularity.
    - Add get_structured_grading_instructions.py to include the new SGI auto-generation feature
4. **Model and Utility Improvements:**
   - Added new models for Structured Grading Instructions.
   - Added new utility functions to support the core functionality changes
5. **Prompt Updates:** Refined existing prompts and added new ones to support the automatic SGI generation

### Steps for Testing

1. Make direct API calls to the /feedback_suggestions endpoint of the module.
2. Test with various diagram types (BPMN, UML Class, UML Activity, etc.) to ensure the functionality works for all Apollon-supported diagrams.
3. Test both scenarios where Structured Grading Instructions (SGIs) are manually provided and where they are not.
4. Verify that appropriate feedback is generated in both cases.

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Athena/athena-test1)](https://athena-test1.ase.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Athena/athena-test2)](https://athena-test2.ase.cit.tum.de)

### Screenshots

2024-09-12 18:35 UTC, FelixTJDietrich requested changes
Please resolve the conflicts

2024-09-15 18:19 UTC, undernagruzez reviewed
Two small suggestions
Also a question: why do we need the parser scripts in this PR? Weren't they already merged in the previous PR?

2024-09-15 18:19 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/apollon_transformer/parser/element.py
> +class Element:
Is it possible to give the class a more specific name? Element seems to be too general.

2024-09-15 18:19 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/apollon_transformer/parser/element.py
> +
```suggestion
```

2024-09-23 14:20 UTC, maximiliansoelch requested changes

2024-09-23 14:20 UTC, maximiliansoelch commented on playground/package-lock.json
Should this change be part of this PR?

2024-09-23 14:20 UTC, maximiliansoelch commented on playground/.gitignore
Should this change be part of this PR?

2024-09-23 14:20 UTC, maximiliansoelch commented on modules/modeling/module_modeling_llm/module_modeling_llm/utils/predict_and_parse.py
> -    """
Why is this comment outdated?

2024-09-23 21:26 UTC, maximiliansoelch commented on modules/modeling/module_modeling_llm/module_modeling_llm/utils/predict_and_parse.py
> -    """
Will be added in a follow up again

2024-09-23 21:33 UTC, maximiliansoelch approved these changes

2024-09-23 21:35 UTC, merged