´Playground´: Side by Side Expert Evaluation (WIP)
pal03377/Athena-New pull request #345
Opened 2024-10-02 09:09 UTC by DominikRemo

### Motivation and Context

### Description

### Steps for Testing

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Athena/athena-test1)](https://athena-test1.ase.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Athena/athena-test2)](https://athena-test2.ase.cit.tum.de)

### Screenshots

2024-11-12 15:01 UTC, FelixTJDietrich requested changes

2024-11-12 15:01 UTC, FelixTJDietrich commented on playground/package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
Please pin the dependencies

2024-11-12 15:01 UTC, FelixTJDietrich commented on playground/src/model/data_mode.ts
> +export type DataMode = "example" | "evaluation" | "expert_evaluation" | "expert_evaluation/exercises" | string;
Why do you have two different modes here insted of just one mode?

2024-11-13 09:52 UTC, FelixTJDietrich approved these changes, later dismissed
Just implement the comments from above, this PR looks good to me. I also tested again on the test server and could not see any issues with it. Good job!

2024-11-18 10:33 UTC, maximiliansoelch approved these changes, later dismissed
Please incorporate the changes requested by @FelixTJDietrich.
Otherwise, it looks good! Great job 👍

2024-11-18 11:15 UTC, DominikRemo commented on playground/package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
We now pinned the dependencies 👍

2024-11-18 11:15 UTC, DominikRemo commented on playground/src/model/data_mode.ts
> +export type DataMode = "example" | "evaluation" | "expert_evaluation" | "expert_evaluation/exercises" | string;
Good catch! This was part of a previous iteration for storing evaluations. It is not needed anymore. We have now removed it 👍

2024-11-18 11:27 UTC, FelixTJDietrich approved these changes

2024-11-18 11:27 UTC, merged