`Modeling Exercises`: Refactor Feedback Reference (#354)
pal03377/Athena-New pull request #354
Opened 2024-11-16 18:50 UTC by LeonWehrhahn

### Motivation and Context

This PR introduces two changes:

1. **Simplified Feedback Schema**: The feedback schema has been simplified by replacing the list of `element_ids` with a single `reference` field. This change avoids unnecessary conversions on the Artemis side and aligns the reference format with how manual references are handled in Artemis.

2. **Enabled Detailed Element Referencing**: Previously, feedback could only reference entire elements. With this update, feedback can now reference specific attributes, methods within elements and also references between elements.

### Description

#### 1. Simplified Feedback Schema

- **Updated Data Models**: Modified the `DBModelingFeedback` and `ModelingFeedback` models to replace the `element_ids` field with a `reference` field that accepts a single string in the format `elementType:elementId` (e.g., `ClassAttribute:5a337bdf-da00-4bd0-a6f0-78ba5b84330e`).

#### 2. Enabled Detailed Element Referencing

- **Enhanced Parsers and Transformers**:
  - Updated the `ApollonJSONTransformer` and its parsers to extract IDs and types of attributes, methods, and relations.
  - Modified the `Element` and `UMLParser` classes to support detailed mapping between element names and their IDs/types.

- **Adjusted Prompts and Utility Functions**:
  - Updated the feedback generation prompt to instruct the LLM to reference specific attributes, methods, and relations using the new format.
  - Modified utility functions like `convert_to_athana_feedback_model` and `get_exercise_model` to handle the new `reference` field and support the enhanced referencing capabilities.

### Steps for Testing

1. **API Testing**:
   - Make direct API calls to the `/feedback_suggestions` endpoint of the module.
   - Use submissions that include classes with attributes, methods, and relations.

2. **Verify Feedback Generation**:
   - Ensure that feedback is generated correctly without errors.
   - Check that the feedback includes the new `reference` field in the format `elementType:elementId`.

3. **Check Granular Referencing**:
   - Verify that feedback can reference specific attributes, methods, and relations.
     - For example, feedback might reference `ClassAttribute:[attribute-id]` or `ClassMethod:[method-id]`.

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Athena/athena-test1)](https://athena-test1.ase.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Athena/athena-test2)](https://athena-test2.ase.cit.tum.de)

### Screenshots

Example of how attribute and method referencing is displayed in the feedback UI on Artemis:
<img width="729" alt="image" src="https://github.com/user-attachments/assets/4e927f46-36da-4388-9a0b-0f060db87511">

2024-11-24 12:58 UTC, DominikRemo submitted a review, later dismissed
Code LGTM

2024-11-24 16:30 UTC, undernagruzez reviewed
Looks good, left a couple of comments

2024-11-24 16:30 UTC, undernagruzez commented on athena/athena/schemas/modeling_feedback.py
> +    reference: Optional[str] = Field(None, description="reference to the diagram element", example="ClassAttribute:5a337bdf-da00-4bd0-a6f0-78ba5b84330e")
Is there a reason for the type none?

2024-11-24 16:30 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/apollon_transformer/parser/element.py
> +        # For attributes, split on ':'
Can it be the case that both are present?

2024-11-24 16:30 UTC, undernagruzez commented on modules/modeling/module_modeling_llm/module_modeling_llm/models/assessment_model.py
> +    element_name: Optional[str] = Field(description="Referenced diagram element, attribute names, and relations (use format: <ClassName>, <ClassName>.<AttributeName>, <ClassName>.<MethodName>, R<numb
Since we don't have a list of feedbacks any more, do we use multiple instances of FeedbackModel somehow now?

2024-11-25 01:12 UTC, EneaGore reviewed
Code lgtm generally. Is there a reason it does not work for the BPMN exercises on TS1 example data?

2024-11-25 15:58 UTC, LeonWehrhahn commented
> Code lgtm generally. Is there a reason it does not work for the BPMN exercises on TS1 example data?

@EneaGore This should be related to the playground token config, if you increase the `Max Tokens` the error should go away.

2024-12-06 17:26 UTC, maximiliansoelch requested changes

2024-12-06 17:26 UTC, maximiliansoelch commented on athena/athena/models/db_modeling_feedback.py
> +    element_ids: Optional[list[str]] = Column(JSON) # type: ignore
Can you add a todo comment to remove that in the future?

2024-12-06 17:26 UTC, maximiliansoelch commented on athena/athena/schemas/modeling_feedback.py
>      element_ids: Optional[List[str]] = Field([], description="referenced diagram element IDs", example=["id_1"])
Can you add a todo comment to remove that in the future?

2024-12-08 15:52 UTC, maximiliansoelch approved these changes

2024-12-08 15:53 UTC, merged