strategy pattern
pal03377/Athena-New pull request #385
Opened 2024-12-31 15:56 UTC by EneaGore

### Motivation and Context

### Description

### Steps for Testing

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Athena/athena-test1)](https://athena-test1.ase.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Athena/athena-test2)](https://athena-test2.ase.cit.tum.de)

### Screenshots

2025-01-13 10:03 UTC, FelixTJDietrich requested changes

2025-01-13 10:03 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/chain_of_thought_approach/generate_suggestions.py
> +async def generate_suggestions(exercise: Exercise, submission: Submission, config: ApproachConfig, debug: bool) -> List[Feedback]:
Why can't this be `ChainOfThoughtConfig`? I think using `ApproachConfig` is too generic, how can you access the config of the approach then?

2025-01-13 10:03 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/approach_controller.py
> +            SuggestionStrategyFactory.initialize_strategies()
Maybe you should just do this on the top level when the module loads? But idk, this works

2025-01-13 10:03 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/approach_controller.py
> +class SuggestionStrategyFactory:
How are the strategies listed for the playground? We still need this union type. Also, is it possible to move it to the athena package instead of keeping it specific to the text module. We can also refactor it in a second step, but this would also be nice for other modules.

2025-01-13 10:03 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/approach_config.py
>      type: str = Field(..., description="The type of approach config")
If you are anyways doing discovering stuff dynamically and using the class name etc. you could also just skip this field and use the class's name 🤔

2025-01-13 10:03 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/approach_controller.py
> +class SuggestionStrategyFactory:
Keeping it for every module would also make it easier when dealing with the playground implementation. I think we'd need to update the config schema endpoint to respond with all discovered strategy configs.

2025-01-13 15:05 UTC, EneaGore commented on modules/text/module_text_llm/module_text_llm/chain_of_thought_approach/generate_suggestions.py
> +async def generate_suggestions(exercise: Exercise, submission: Submission, config: ApproachConfig, debug: bool) -> List[Feedback]:
It still works the same because of Polymorphism, I had to use the generic ApproachConfig to avoid a circular import, when the ChainofThoughtConfig is passed it works the same.

2025-01-14 15:01 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/approach_config.py
>      type: str = Field(..., description="The type of approach config")
it's fine as is

2025-01-20 13:59 UTC, FelixTJDietrich approved these changes, later dismissed
I will apply the one suggestion that changes the formatting, the rest looks pretty good

2025-01-20 13:59 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/basic_approach/generate_suggestions.py
> +async def generate_suggestions(exercise: Exercise, submission: Submission, config:ApproachConfig, debug: bool, is_graded: bool) -> List[Feedback]:
```suggestion
async def generate_suggestions(exercise: Exercise, submission: Submission, config: ApproachConfig, debug: bool, is_graded: bool) -> List[Feedback]:
```
space

2025-01-20 13:59 UTC, FelixTJDietrich commented on modules/text/module_text_llm/module_text_llm/create_approach_script.py
Cool script, maybe document its existence in the future. But I think some students might find it. I think we can keep it as is

2025-01-20 14:01 UTC, FelixTJDietrich approved these changes

2025-01-20 14:04 UTC, merged