Add pull request template
pal03377/Athena-New pull request #41
Opened 2023-06-29 09:57 UTC by FelixTJDietrich

### Motivation and Context

We don't have a PR template for this repository at the moment.

### Description

Add a pull request template. 

### Issues
- Should we add more? As in a checklist or review process etc.

2023-06-29 16:46 UTC, pal03377 requested changes
I would remove the line about screenshots in docker. Otherwise, this is a good start!

2023-06-29 16:46 UTC, pal03377 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Create a GIF file from a screen recording in a docker container https://toub.es/2017/09/11/high-quality-gif-with-ffmpeg-and-docker/ -->
```suggestion
```
I don't think this line makes sense for us.

2023-06-30 06:18 UTC, FelixTJDietrich commented
I will just merge it and we do a follow up at the end of our MTs or when a new person comes to the repository

2023-06-30 23:24 UTC, pal03377 approved these changes

2023-06-30 23:24 UTC, merged