Add export for evaluation data from Artemis
pal03377/Athena-New pull request #42
Opened 2023-06-29 15:47 UTC by FelixTJDietrich

### Motivation and Context
 
 

As mentioned in #35, moving the export scripts into this repository would make it easier for people to get access to evaluation data within the Playground. This also allow for better reproducibility of the evaluation results.

 ### Description
 

This adds some export scripts to the playground:
1. `npm run export:artemis:1-load-anonymized-database-dump`
2. `npm run export:artemis:2-export-evaluation-data`
3. `npm run export:artemis:3-download-programming-repositories`
4. `npm run export:artemis:4-link-programming-repositories`

- [x] Add helper script to load the anonymized database dump
- [x] Add text exercises export -> Following the text exercise schema
- [x] Add programming exercises export -> Following the programming exercise schema
    - [x] Export repository download instructions for material and submissions
    - **Note:** Repository urls will be null 
- [x] Add programming exercise material and submissions (participation) export
    - Executed by the course instructor (but not independent of the Athena repository 🤔)
    - **Input:** List of participations and exercises to download (provided by `scripts/artemis/evaluation/programming_exercises.json`
    - **Output:** Downloads all the materials and anonymized submissions `data/evaluation`
- [x] Link and validate materials and submissions with the `exercise-*.json`
- [x] Add note about signing the NDA with the chair and getting the database dump (general README)

 ### Steps for Testing
 

#### Prerequisites

1. `cd playground`
2. `npm install`

#### Loading the database dump
**Note:** If you have already loaded the anonymized database dump I recommend to skip this!  
*Loading the dump takes about 30min and will probably fail due to the volume running out of storage if you have already loaded a dump under a different name. I think the delete database and recreate option takes also a long time to delete.*

1. Run `npm run export:artemis:1-load-anonymized-database-dump`
2. Configure the mysql database connection, by default it will use the Artemis dev config
3. Input a database name where the anonymized database dump should be loaded into
4. Copy and enter the whole path of the database dump, i.e. `/Users/.../Downloads/artemis_database_dump_anonymized_2023_03_29.sql`
6. Wait for it to finish
7. The database is now populated with the database dump 

#### Exporting Evaluation Data

1. Get Artemis running locally
2. Create a text and programming exercise with some submissions (and feedback)
3. In `playground/scripts/artemis/evaluation/*` replace the exercises for testing purposes with the id(s) for text exercises under `"text": [...]` and for programming exercises under `"programming": [...]`. It will search recursively: `{ id: 1 }` works as config.
4. Run `npm run export:artemis:2-export-evaluation-data`
5. Connect with your `artemis` database (NOT `anonymized_artemis` in this case!)
6. Script should finish and populate `data/evaluation` with the `exercise-*.json` files

#### Exporting Exercise Material and Submission

1. Same as `Exporting Evaluation Data` step 1. to 3.
2. Run `npm run export:artemis:3-download-programming-repositories`
3. It should download the material and submissions to `data/evaluation` using the `text/programming_exercises.json`

> For getting the associated materials and submissions of the anonymized database dump we have to get an Artemis instructor to clone the repo, `npm install`, and run `npm run export:artemis:3-download-programming-repositories`.

#### Link Exercise Material and Submission (Programming Exercises)

1. Run `npm run export:artemis:4-link-programming-repositories`
2. It will search for programming exercises `exercise-*.json` and link them with the `exercise-*/`'s materials and submissions

#### Playground Testing

1. Start the playground
3. Select a module and `evaluation data`
4. Check if the data is there and can be used for playground requests.

 ### Screenshots

2023-07-13 02:43 UTC, pal03377 requested changes
Code review only (also, I did go over all the export scripts, but did not deep-dive into them). If I remember correctly, @maximiliansoelch will try exporting some iPraktikum data using this. After my code change requests are resolved and this worked, we can merge.

2023-07-13 02:43 UTC, pal03377 commented on playground/README.md
> +# Playground
Should this be on a documentation page instead of a README?

2023-07-13 02:43 UTC, pal03377 commented on playground/README.md
> +npm run export:artemis:export:artemis:1-load-anonymized-database-dump
There is `export` twice written in here. Error?

2023-07-13 02:43 UTC, pal03377 commented on playground/README.md
> +If you want to use the programming exercises, you will have to request them separately from the Artemis team, they are not included in the anonymized database dump. An instructor of the course can ex
```suggestion
If you want to use the programming exercises, request them separately from the Artemis team: They are not included in the anonymized database dump. An instructor of the course can export the programming exercises from Artemis using the following command:
```

2023-07-13 02:43 UTC, pal03377 commented on playground/README.md
> +This will load the data into your local Mysql database (just reuse your Artemis database).
```suggestion
This will load the data into your local MySQL database (just reuse your Artemis database). 
```

2023-07-13 02:43 UTC, pal03377 commented on playground/README.md
> +
```suggestion

```

2023-07-13 02:43 UTC, pal03377 commented on playground/package.json
> +    "export:artemis:4-link-materials-and-submissions": "node ./scripts/artemis/link_materials_and_submissions.mjs"
Idea: The MJS files can also be named with `1-`, `2-`, ... in front.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/db_config.mjs
> +    },
Personally, I'd like to be able to change the port as well. I don't have the anonymized dump in my local DB, but instead, I have a separate DB that needs to run on another port if I want to be able to access both of them at the same time.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/db_config.mjs
> +export { loadDBConfig };
```suggestion
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/db_config.mjs
> +async function loadDBConfig() {
```suggestion
export async function loadDBConfig() {
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_evaluation_data.mjs
> +    console.log(`No ${exerciseType} exercises to export in ${inputDataPath}`);
```suggestion
    console.warn(`No ${exerciseType} exercises to export in ${inputDataPath}`);
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_evaluation_data.mjs
> +  );
```suggestion
  console.log(`Found ${exerciseIds.length} ${exerciseType} exercises to export in ${inputDataPath}`);
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_evaluation_data.mjs
> +  sql = sql.replace(":exercise_ids", `(${placeholders})`);
Add a comment for explanation here please.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_evaluation_data.mjs
> +    exercises.forEach(async ({ exercise_data }) => {
Problem: The `async` function in the `forEach` won't be awaited. Therefore, the success message will be shown too early. Solution suggestion:
```suggestion
    await Promise.all(exercises.map(async ({ exercise_data }) => {
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_evaluation_data.mjs
> +async function executeQuery(config) {
I would like to have some documentation here

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_evaluation_data.mjs
> +async function exportExercises(
I'd like to have some documentation for this function.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_evaluation_data.mjs
> +      "\nNote: For programming exercises you have to still export the materials and submissions and link them using another two npm scripts."
I honestly don't get what this sentence means. On the other hand, it's quite late already and maybe I just can't process it right now 😅

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +const auth = async () => {
```suggestion
async function auth() {
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    password: password,
Just if you want to feel cool:
```suggestion
    username,
    password,
```

(The fact that this works can at least be quite handy to know when reading other JS code sometimes.)

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    const jwt = response.headers["set-cookie"][0].split(";")[0].split("=")[1];
Is there no better way? This seems a bit error-prone.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +  const response = await axiosInstance.post("/public/authenticate", {
Why are you using axios? The normal `fetch` API is super powerful nowadays.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +const downloadMaterial = async (exerciseId) => {
```suggestion
async function downloadMaterial(exerciseId) {
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +  if (response.status === 200) {
Consider catching the error first instead, cancelling and then continuing with the success path with one less indentation (same concept as `guard` in Swift).

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +  if (response.status === 200) {
Consider handling the error first.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    );
```suggestion
    const exercisePath = path.join(evaluationOutputDirPath, `exercise-${exerciseId}`);
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    const zipFile = files.find((file) => file.endsWith(".zip"));
```suggestion
    const zipFile = Object.keys(materialData.files).find((file) => file.endsWith(".zip"));
```
Simple enough this way. The `files` variable isn't used anywhere else as far as I see.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +      const zipFile = materialZipFiles.find((file) =>
```suggestion

    const writeZip = async (kind) => {
      const zipFile = Object.keys(materialZipData.files).find((file) =>
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +        );
Can you elaborate what this does in a comment?

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +            if (!zipData.files[file].dir) {
Is there no `.file`? Would look safer and more understandable.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    await Promise.all(["exercise", "solution", "tests"].map(writeZip));
This will do everything in parallel. That's intended, right?

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +const downloadSubmissions = async (exerciseId) => {
```suggestion
async function downloadSubmissions(exerciseId) {
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    );
```suggestion
    const submissionsPath = path.join(evaluationOutputDirPath, `exercise-${exerciseId}`, "submissions");
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +const download = async (exerciseId) => {
```suggestion
async function download(exerciseId) {
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +const main = async () => {
```suggestion
async function main() {
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    default: "https://artemis.ase.in.tum.de",
More future-proof:
```suggestion
    default: "https://artemis.cit.tum.de",
```

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/link_materials_and_submissions.mjs
> +exercises.forEach((exercise) => {
```suggestion
for (let exercise of exercises) {
```
Personally, I find this to be more readable.

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/load_anonymized_database_dump.mjs
> +  return new Date(seconds * 1000).toISOString().substr(11, 8);
`String.prototype.substr` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/load_anonymized_database_dump.mjs
> +    for await (const line of rl) {
Wow, that works? TIL

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/load_anonymized_database_dump.mjs
> +    }
For this block, I'd like to see some more comments about why there needs to be all this pre-processing

2023-07-13 02:43 UTC, pal03377 commented on playground/scripts/artemis/utils.mjs
> +export const findExerciseIds = (inputData, acc) => {
```suggestion
export function findExerciseIds(inputData, acc) {
```

2023-07-16 16:22 UTC, FelixTJDietrich commented on playground/scripts/artemis/db_config.mjs
> +    },
Will add it

2023-07-16 16:39 UTC, FelixTJDietrich commented on playground/scripts/artemis/export_evaluation_data.mjs
> +      "\nNote: For programming exercises you have to still export the materials and submissions and link them using another two npm scripts."
Improved wording 😅

2023-07-16 16:42 UTC, FelixTJDietrich commented on playground/scripts/artemis/export_evaluation_data.mjs
> +    exercises.forEach(async ({ exercise_data }) => {
Thanks for finding that!

2023-07-16 18:20 UTC, FelixTJDietrich commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +  const response = await axiosInstance.post("/public/authenticate", {
Good point, I thought that node only scripts don't support `fetch` as a built-in functionality. But TIL that it is now supported since Node.js 18.

2023-07-16 19:06 UTC, FelixTJDietrich commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +  const response = await axiosInstance.post("/public/authenticate", {
Now using fetch :)

2023-07-16 19:07 UTC, FelixTJDietrich commented on playground/README.md
> +npm run export:artemis:export:artemis:1-load-anonymized-database-dump
Ops. Thanks!

2023-07-16 19:08 UTC, FelixTJDietrich commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    const jwt = response.headers["set-cookie"][0].split(";")[0].split("=")[1];
I tried to improve it

2023-07-16 20:25 UTC, FelixTJDietrich commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +            if (!zipData.files[file].dir) {
Should be better now, thanks for the suggestion!

2023-07-16 20:26 UTC, FelixTJDietrich commented on playground/scripts/artemis/export_materials_and_submissions.mjs
> +    await Promise.all(["exercise", "solution", "tests"].map(writeZip));
Yeah this is fine and intended.

2023-07-16 20:31 UTC, FelixTJDietrich commented on playground/scripts/artemis/load_anonymized_database_dump.mjs
> +  return new Date(seconds * 1000).toISOString().substr(11, 8);
Thanks, I was confused about this. VSCode did not show `substring` to me

2023-07-16 20:48 UTC, FelixTJDietrich commented on playground/scripts/artemis/load_anonymized_database_dump.mjs
> +    }
I added some comments

2023-07-16 20:58 UTC, FelixTJDietrich commented on playground/package.json
> +    "export:artemis:4-link-materials-and-submissions": "node ./scripts/artemis/link_materials_and_submissions.mjs"
I renamed the scripts and filenames to have better names 👍

2023-07-16 21:25 UTC, FelixTJDietrich commented on playground/README.md
> +# Playground
I created documentation pages now and removed the readme

2023-07-17 02:59 UTC, pal03377 approved these changes
Code looks good 🎉  Do you want to merge right now or wait for the iPraktikum data? I'm find with both, but would tend to merging.

2023-07-17 02:59 UTC, pal03377 commented on docs/index.rst
> +    setup/vscode
Good idea! That will help with the current GitHub warning that's present on all PRs right now.

2023-07-17 02:59 UTC, pal03377 commented on playground/scripts/artemis/3_download_programming_repositories.mjs
> +let baseURL = "https://artemis.cit.tum.de/api";
Does this need a default value here? It's always overwritten anyways, right?

2023-07-17 07:44 UTC, FelixTJDietrich commented
Let's merge it right now, there are some things I want to do as a followup, like importing zips someone downloaded from the Artemis UI. But I will do it once needed.

2023-07-17 07:46 UTC, merged