Add switch LLM model config to playground
pal03377/Athena-New pull request #44
Opened 2023-07-04 08:45 UTC by FelixTJDietrich

### Motivation and Context

### Description

### Steps for Testing

### Screenshots

2023-07-11 21:24 UTC, FelixTJDietrich commented
I don't know where the Prospector Linting error comes from. It says cyclic-import for `module_text_llm/prompts/suggest_feedback_basic.py` but that file does not import anything...

2023-07-13 02:07 UTC, pal03377 requested changes
Wow, this is so incredibly cool! 🥳 I also really like most approaches you took in the code, keeping it extremely clean for module developers 💪 

![screenshot-2023-07-13_001565](https://github.com/ls1intum/Athena/assets/9006596/b49a4621-a978-4c61-9740-f86813acd56c)
![screenshot-2023-07-13_001566](https://github.com/ls1intum/Athena/assets/9006596/7fa2e544-7eb9-48f7-88fc-9f8fa849b304)
![screenshot-2023-07-13_001567](https://github.com/ls1intum/Athena/assets/9006596/4bd84c45-6b82-4176-8558-dadd0f08e60f)

I still have a large number of change requests, see below. Also, it would be good if future PRs could be smaller than this.

2023-07-13 02:07 UTC, pal03377 commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +async def request_to_module(module: Module, module_config: Optional[str], path: str, data: Optional[dict], method: str = "POST") -> ModuleResponse:
Do you need the default value for `method`? I think it would make more sense to omit it.

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/endpoints.py
> +    Callable[[E, List[S], Optional[dict]], Coroutine[Any, Any, None]]
Looks relatively clean, considering how complex those type checks can get! Could you also add comments to these lines, including examples of how such functions would look like?

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/endpoints.py
> +                module_config = None
Why not let the server return an error `400`? This way, the error would be much more discoverable.

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/endpoints.py
> +        if len(inspect.signature(func).parameters) > 2:
IMO this check should be improved. Can you detect that there is a parameter named `module_config` instead? Then, you can pass that to the `kwargs` of the function.

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/endpoints.py
> +            submission = func(*args)
You could create a helper function for this part of the code

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/endpoints.py
> +                module_config = None
Can you also put this into a helper? Maybe you can even switch the `module_config = Header(...)` part in the parameters to another fastapi `Depends`... I'm not sure

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/metadata.py
> +from fastapi import Request
I'm missing some documentation on the top of this file about its purpose

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/metadata.py
> +    return metadata_context.get({})
I like this solution; it's pretty cool! Also, it's still simple to understand how to use it as a module developer

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/metadata.py
> +    # This will return an empty dict if no metadata has been set
I think there should be a more comprehensive documentation of this function as a `"""` docstring. The short information here should be included there.

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/metadata.py
> +class MetaDataMiddleware(BaseHTTPMiddleware):
A usage example (documentation) here would be good

2023-07-13 02:07 UTC, pal03377 commented on athena/athena/metadata.py
> +    # Get the current metadata, add the new key-value pair
I'd like to see another docstring here.

2023-07-13 02:07 UTC, pal03377 commented on docs/module/structure.rst
> +Provide Config Schema
Well done documenting it here!

2023-07-13 02:07 UTC, pal03377 commented on env_example/module_text_llm.env
>  SECRET=12345abcdef
Please remind me to change the config on Athena TS3 to make this work after this PR is merged

2023-07-13 02:07 UTC, pal03377 commented on module_example/module_example/__main__.py
> +    return Configuration.schema()
I think this position is correct. The configuration endpoint is listed on top in the playground, but I think it would be better suited on the bottom like this (although the actual configuration can remain on top in the playground, of course). Most importantly to me, the order of endpoints should be consistent everywhere.

2023-07-13 02:07 UTC, pal03377 commented on module_example/module_example/__main__.py
> +    return Configuration.schema()
This `Configuration.schema` is so cool! Can we have a class decorator for the `Configuration` class? This way, you wouldn't even need to define the endpoint here, just tell `athena` which is the configuration pydantic schema to use!

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/__main__.py
> +    if module_config is not None:
Can we guarantee to module developers that the `module_config` will never be `None` if they request it? If none is provided, we could just generate it from the defaults given by the pydantic schema.

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/config.py
> +class BasicPrompt(Prompt):
Simplify:
```suggestion
class BasicPrompt(BaseModel):
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/config.py
> +)
You should be able to do this with only pydantic defaults. Then, you don't need this variable, and you can let the `athena` package handle the given-value-or-default-choice part.

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/__init__.py
> +    raise EnvironmentError(f"LLM_DEFAULT_MODEL is not set correctly, available models:\n{', '.join(available_models)}")
Please describe how to set `LLM_DEFAULT_MODEL` correctly in this error message. (It would suffice to reference the corresponding example file.)

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/__init__.py
> +)
This should also be possible with only pydantic defaults, I believe.

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/model_config.py
> +        pass
Why not have a `BaseLanguageModel` directly? What do you need this abstract factory class for?

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +azure_openai_available = os.environ.get("LLM_AZURE_OPENAI_API_KEY") is not None
Oof, that's quite ugly. I remember the chats with you about the pain to get this to work, however. Is there some planned point in the future where we will remove this again?

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +# mypy: ignore-errors
Why?

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +# hardcode the model names (i.e. OpenAI fixes their api)
Is there some hope for the future to be able to remove this?

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +def _get_available_deployments(openai_models: dict[str, List[str]], model_aliases: dict[str, str]):
```suggestion
def _get_available_deployments(openai_models: Dict[str, List[str]], model_aliases: Dict[str, str]):
```
I usually prefer `dict`, but then you don't support Python 3.8. I'm not sure if we even want to, but only uppercasing all built-in types seems like a low price to pay for that, so I think we should keep them capitalized.

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    available_deployments: dict[str, dict[str, Any]] = {
```suggestion
    available_deployments: Dict[str, Dict[str, Any]] = {
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +                        available_deployments["fine_tuneing"][deployment.id] = deployment
```suggestion
            deployments = openai.Deployment.list().get("data") or []  # type: ignore
            for deployment in deployments:
                model_name = deployment.model
                if model_name in model_aliases:
                    model_name = model_aliases[model_name]
                if model_name in openai_models["chat_completion"]:
                    available_deployments["chat_completion"][deployment.id] = deployment
                elif model_name in openai_models["completion"]:
                    available_deployments["completion"][deployment.id] = deployment
                elif model_name in openai_models["fine_tuneing"]:
                    available_deployments["fine_tuneing"][deployment.id] = deployment
```

Suggestion - I'm unsure if it's better, but it's one less indentation.

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    available_models: dict[str, BaseLanguageModel] = {}
```suggestion
    available_models: Dict[str, BaseLanguageModel] = {}
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +            available_models[f"{OPENAI_PREFIX}{model_name}"] = ChatOpenAI(
This looks simpler:
```suggestion
            available_models[OPENAI_PREFIX + model_name] = ChatOpenAI(
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +            available_models[f"{OPENAI_PREFIX}{model_name}"] = OpenAI(
```suggestion
            available_models[OPENAI_PREFIX + model_name] = OpenAI(
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +            available_models[f"{AZURE_OPENAI_PREFIX}{deployment_name}"] = AzureChatOpenAI(
```suggestion
            available_models[AZURE_OPENAI_PREFIX + deployment_name] = AzureChatOpenAI(
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +            available_models[f"{AZURE_OPENAI_PREFIX}{deployment_name}"] = AzureOpenAI(
```suggestion
            available_models[AZURE_OPENAI_PREFIX + deployment_name] = AzureOpenAI(
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +        for deployment_name, deployment in available_deployments["completion"].items():
Can't you loop over the key on `available_deployments` here to avoid writing the loop twice? `for deployment_type in "chat_completion", "completion":`

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    openai_models, _model_aliases)
```suggestion
available_deployments = _get_available_deployments(openai_models, _model_aliases)
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +                   name: name for name in available_models})
```suggestion
OpenAIModel = Enum('OpenAIModel', {name: name for name in available_models})
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    default_openai_model = OpenAIModel["gpt-3.5-turbo"]
```suggestion
default_openai_model = OpenAIModel[os.environ.get("LLM_DEFAULT_MODEL", "gpt-3.5-turbo")]
```

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +class OpenAIModelConfig(ModelConfig):
Maybe add a docstring?

2023-07-13 02:07 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +                    model_kwargs[attr] = value
Can you add more comments about what you're doing here, please?

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/base_info_header.tsx
> +  onChangeModuleConfig: (value: any | undefined) => void;
```suggestion
  onChangeModuleConfig: (value: any) => void;
```

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/base_info_header.tsx
> +  moduleConfig: any | undefined;
```suggestion
  moduleConfig: any;
```
To my knowledge, `any` already allows for `undefined` values.

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/form/description_field.tsx
> +}
In case this is from somewhere else, please link to the source. If it is not: Wow! :D

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/form/utils.ts
> +  const paths = toPathSchema(validator, schema, undefined, schema);
Please add a comment about what this does.

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/module_config/default_schema_form.tsx
> +import { ModuleConfigProps } from ".";
What is this? I've never seen an import `from "."` in JS/TS 🤔

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/module_config/module_llm.tsx
> +export default function ModuleLLMConfig({
I don't immediately see which additional config UI elements this adds. Also, are you sure that it's not possible to render a good UI without any custom components? I really like the idea of "not caring" in the playground and just showing all available automatically gained options. In any case, an additional comment wouldn't hurt.

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/module_config/index.tsx
> +};
I'm a bit sad that this is needed 😞 
If it is really required, can you add some info on how to add something here? I suppose you have to rewrite `type CustomModuleConfig = "module_text_llm";` to `type CustomModuleConfig = "module_text_llm" | "my_new_module";`? If so, that's not so obvious.

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/module_config/index.tsx
> +  moduleConfig: any | undefined;
```suggestion
  moduleConfig: any;
```

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/module_requests/get_config_schema.tsx
> +    );
Not for this PR, but we should probably abstract away these kinds of requests in some later follow-up.

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/module_requests/request_feedback_suggestions.tsx
> +          }),
If `moduleConfig` is `undefined`, will the spread operator still work properly?

2023-07-13 02:07 UTC, pal03377 commented on playground/src/components/module_requests/request_submission_selection.tsx
> +    if (!response || response.status !== 200 || typeof response.data.data !== "number") {
```suggestion
    if (!response || response.status !== 200 || typeof response.data.data !== "number") {
```
It looks like a code smell to me that you must write `.data.data` here.

2023-07-13 02:07 UTC, pal03377 commented on playground/src/helpers/athena_fetcher.ts
> +  };
This looks like the reused fetching function I talked about earlier! Why is it not used everywhere?

2023-07-13 02:07 UTC, pal03377 commented on playground/src/helpers/athena_fetcher.ts
> +  async (url: string) => {
Make this a class? Then you can also directly `export default class` it.

2023-07-13 02:07 UTC, pal03377 requested changes
Wow, this is so incredibly cool! 🥳 I also really like most approaches you took in the code, keeping it extremely clean for module developers 💪 

![screenshot-2023-07-13_001565](https://github.com/ls1intum/Athena/assets/9006596/b49a4621-a978-4c61-9740-f86813acd56c)
![screenshot-2023-07-13_001566](https://github.com/ls1intum/Athena/assets/9006596/7fa2e544-7eb9-48f7-88fc-9f8fa849b304)
![screenshot-2023-07-13_001567](https://github.com/ls1intum/Athena/assets/9006596/4bd84c45-6b82-4176-8558-dadd0f08e60f)

I still have a large number of change requests, see below. Also, it would be good if future PRs could be smaller than this.

2023-07-13 02:08 UTC, pal03377 commented
What I also currently don't like: The assessment module manager returns an object with `data` nested twice (because it wraps the module response, which wraps the return value of the function):
![screenshot-2023-07-13_001568](https://github.com/ls1intum/Athena/assets/9006596/35260f2e-f6e9-421b-8553-48f7d9a094a0)

2023-07-13 08:53 UTC, FelixTJDietrich commented on playground/src/components/module_requests/request_feedback_suggestions.tsx
> +          }),
Yes, the undefined case was also the reason for doing it like this. 
<img width="470" alt="image" src="https://github.com/ls1intum/Athena/assets/5898705/526cb269-67e3-4d1a-8e41-76cb706b9a3e">

2023-07-13 10:23 UTC, FelixTJDietrich commented on athena/athena/endpoints.py
> +    Callable[[E, List[S], Optional[dict]], Coroutine[Any, Any, None]]
Done

2023-07-13 13:21 UTC, FelixTJDietrich commented on env_example/module_text_llm.env
>  SECRET=12345abcdef
Will do :)

2023-07-13 13:27 UTC, FelixTJDietrich commented on module_example/module_example/__main__.py
> +    return Configuration.schema()
Hmm, I can do it for now. I will also add something that replaces `anyOf` with `oneOf` in the schema for union types. 

I thought maybe pydantic cannot cover all cases but for the near future this will probably be enough and also easier to understand. If someone runs into limitations they can replace it with a abstract class that supports `.schema()`

2023-07-13 13:33 UTC, FelixTJDietrich commented on playground/src/components/module_requests/request_submission_selection.tsx
> +    if (!response || response.status !== 200 || typeof response.data.data !== "number") {
fixed

2023-07-13 15:54 UTC, FelixTJDietrich commented on module_example/module_example/__main__.py
> +    return Configuration.schema()
Nevermind about the `anyOf` for now, the `Union` type seems to work. It is much better now :)

2023-07-13 15:54 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/config.py
> +)
Done

2023-07-14 07:23 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/model_config.py
> +        pass
I want to do `.schema()`, it does support it but there are also things I don't want to configure and things that are omitted I think. This is just cleaner and I have more control of which configurations to expose.

Langchain is also a bit hacky and some config is not specified in the pydantic model (c.f. chat models `presence_penalty`, `top_p`, ...).

2023-07-14 07:32 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +# mypy: ignore-errors
Fixed it, now using `# pylint: disable=protected-access` (suddenly works for me)

2023-07-14 07:36 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +azure_openai_available = os.environ.get("LLM_AZURE_OPENAI_API_KEY") is not None
I will keep it for now like this.

What I might want to do in the future is to also allow dropping the `LLM_` prefix again, then you can either use azure or non-azure. But right now for development and evaluation having the option to use both is quite handy.

2023-07-14 07:38 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +# hardcode the model names (i.e. OpenAI fixes their api)
Right now no, the openai azure and non-azure api are somewhat different but are exposed via one library `openai`. It would be amazing if I could import it twice as `openai` and `azure_openai`

2023-07-14 07:41 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +# hardcode the model names (i.e. OpenAI fixes their api)
I just saw that this is also possible with some trick to get around the caching. But then I would have the problem with langchain.

2023-07-14 07:42 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +def _get_available_deployments(openai_models: dict[str, List[str]], model_aliases: dict[str, str]):
Okay

2023-07-14 07:45 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    default_openai_model = OpenAIModel["gpt-3.5-turbo"]
Good point

2023-07-14 08:50 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/__main__.py
> +    if module_config is not None:
Done, it is now guaranteed :) Good idea

2023-07-14 10:19 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +    openai_models, _model_aliases)
I don't know why the formatter always does this...

2023-07-14 13:12 UTC, FelixTJDietrich commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +                    model_kwargs[attr] = value
I changed it a bit, it should now be less buggy when using multiple configurations of the same model

2023-07-14 13:15 UTC, FelixTJDietrich commented on playground/src/components/base_info_header.tsx
> +  moduleConfig: any | undefined;
Yeah, I like the explicit undefined but I removed it everywhere now.

2023-07-14 13:19 UTC, FelixTJDietrich commented on playground/src/components/form/description_field.tsx
> +}
Yeah it is slightly modified version of https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/templates/DescriptionField.tsx I will link it.

I wanted to enable markdown everywhere by default, so I added the `ReactMarkdown` around the string. They also have a way to enable markdown rendering, but it has some limitations... In case you enable markdown their way, it is using the `else` case ^^

2023-07-14 13:29 UTC, FelixTJDietrich commented on playground/src/components/module_config/default_schema_form.tsx
> +import { ModuleConfigProps } from ".";
This means that I'm importing from the same directory's `index.{js,jsx,ts,tsx}` file.

2023-07-14 13:36 UTC, FelixTJDietrich commented on playground/src/components/module_config/module_llm.tsx
> +export default function ModuleLLMConfig({
It is an opt-in way to customize your config form for the playground. There is a default form that is used and works out of the box, that renders without any custom components. For example `module_example` uses that form and any other future one.

By default, a field is rendered as input field which makes sense to me. For my llm modules, at least `module_text_llm` right now, I want to render a `textarea` for the prompt instead.

2023-07-14 13:42 UTC, FelixTJDietrich commented on playground/src/components/module_config/index.tsx
> +};
I explained the reason for the customisation in the comment above. It is opt-in for when you are not satisfied with the default rendering of the json schema.

2023-07-14 13:47 UTC, FelixTJDietrich commented on playground/src/helpers/athena_fetcher.ts
> +  };
I thought about it but the problem is the `alert(...)` you are doing 😅
I can try to unify it

2023-07-14 19:28 UTC, FelixTJDietrich commented on playground/src/helpers/athena_fetcher.ts
> +  async (url: string) => {
Hmm, I don't see the benefit of a class. I think the more functional approach is fine.

2023-07-14 20:00 UTC, FelixTJDietrich commented on playground/src/helpers/athena_fetcher.ts
> +  };
Nevermind, I remember it was actually the `POST` method that stopped me from it, I only needed a way to `GET` the schema. Let's do it in a folllow-up PR, I created an issue for it: #49

2023-07-14 20:02 UTC, FelixTJDietrich commented
The error you experienced with my module is still on my todo list. I will replace CSV parsing through JSON parsing and improve error handling so this does not happen anymore :S

2023-07-17 02:54 UTC, pal03377 requested changes
Nice changes! I only have larger problems in `request_to_module.py` left now. I also tested it locally again.

Also, I notice that `endpoints.py` is getting more and more complex (which is not really your fault). We might need to think of some refactoring in the future.

2023-07-17 02:54 UTC, pal03377 commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
>  T = TypeVar('T')
Maybe rename `T` to `D` so that it's clearer that one is for Data and the other for Metadata?

2023-07-17 02:54 UTC, pal03377 commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        headers['X-Module-Config'] = module_config
```suggestion
headers = {}
if module_secret:
    headers['X-API-Secret'] = module_secret
if module_config:
    headers['X-Module-Config'] = module_config
```

Does something break if `headers` is `{}` instead of None? If no, the above simplification looks slightly better to me.

2023-07-17 02:54 UTC, pal03377 commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +                response = await client.get(path, headers=headers)
```suggestion
            if method == "POST":
                response = await client.post(path, json=data, headers=headers)
            elif method == "GET":
                response = await client.get(path, headers=headers)
            else:
                raise ...
```
`PUT` and `DELETE` requests are also possible. These would currently just get converted into `GET` requests.

2023-07-17 02:54 UTC, pal03377 commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        pass
I don't get this change. As far as I see, the new code segment here never does anything (either it raises and then catches or not).

2023-07-17 02:54 UTC, pal03377 commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        response_data = response.text
Should there be a log here?

2023-07-17 02:54 UTC, pal03377 commented on athena/athena/endpoints.py
> +    Examples:
Very nice! When I suggested these comments, I imagined them to be inline and next to the types, but this is even better 🎉

2023-07-17 02:54 UTC, pal03377 commented on athena/athena/endpoints.py
> +    Callable[[E, S, C], Coroutine[Any, Any, List[F]]]
I just noticed that the order here differs from the examples' order. Can you re-order the types?

2023-07-17 02:54 UTC, pal03377 commented on athena/athena/endpoints.py
> +    return cls
It's probably better if you don't change this, but to boast the knowledge I gained last semester in the `Advanced Python Programming` course a bit: This looks like a perfect use case for a metaclass :) You would define the metaclass and a base class to inherit from. I'll leave 100% of the choice whether you want to do this to you; metaclasses can be quite a complex beast, so maybe the code wouldn't even improve.

2023-07-17 02:54 UTC, pal03377 commented on athena/athena/metadata.py
> +"""
Wow, that's a really good docstring!

2023-07-17 02:54 UTC, pal03377 commented on module_example/module_example/__main__.py
> +        emit_meta('_comment', 'You can add any meta data you want here')
Why is it `_comment` and not just `_comment` here?

2023-07-17 02:54 UTC, pal03377 commented on module_example/module_example/__main__.py
> +        emit_meta('costs', '100.00€')
```suggestion
        emit_meta("costs", "100.00€")
```
consistency

2023-07-17 02:54 UTC, pal03377 commented on module_text_llm/module_text_llm/helpers/models/openai.py
> +# hardcode the model names (i.e. OpenAI fixes their api)
:( ok

I'll close my eyes for a second 🙈

2023-07-17 02:54 UTC, pal03377 commented on module_text_llm/module_text_llm/prompts/suggest_feedback_basic.py
>  """
TIL that that's possible 😮

2023-07-17 02:54 UTC, pal03377 commented on playground/src/components/module_config/module_llm.tsx
> +export default function ModuleLLMConfig({
Ok, makes sense 👍

2023-07-17 02:54 UTC, pal03377 commented on playground/src/components/module_requests/request_feedback_suggestions.tsx
> +          }),
Ah, interesting!

2023-07-17 02:54 UTC, pal03377 commented on playground/src/components/module_requests/request_submission_selection.tsx
> +        meta: {},
We should be able to omit this, right? We might need to change the `ModuleResponse` type instead.

2023-07-17 02:54 UTC, pal03377 commented on playground/src/components/module_response_view.tsx
> +  }
```suggestion
  try {
    formattedData = JSON.parse(formattedData);
  } catch (e) {
    // continue to show the non-formatted response string
  }
  try {
    formattedMeta = JSON.parse(formattedMeta);
  } catch (e) {
    // continue to show the non-formatted response string
  }
```

Improving my own old comment here, I believe.

2023-07-17 02:54 UTC, pal03377 commented on playground/src/model/module_response.ts
> +  meta: any;
```suggestion
  meta?: any;
```
Does this make all the `meta` changes unnecessary?

2023-07-17 02:54 UTC, pal03377 commented on module_example/module_example/__main__.py
> +        emit_meta('_comment', 'You can add any meta data you want here')
```suggestion
        emit_meta('_comment', 'You can add any metadata you want here')
```

2023-07-17 07:51 UTC, FelixTJDietrich commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        headers['X-Module-Config'] = module_config
That is probably fine, I will test it. Looks also better to me

2023-07-17 08:02 UTC, FelixTJDietrich commented on athena/athena/endpoints.py
> +    Callable[[E, S, C], Coroutine[Any, Any, List[F]]]
Reordered

2023-07-17 08:21 UTC, FelixTJDietrich commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        pass
I guess I will remove `raise_for_status` then?

2023-07-17 08:26 UTC, FelixTJDietrich commented on athena/athena/endpoints.py
> +    return cls
I looked it up and you are right. But this does basically the same and seems to be easier to understand. Let's keep it like this, also you don't have to use `metaclass=...` as a module developer that way.

2023-07-17 08:28 UTC, FelixTJDietrich commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        response_data = response.text
I added one

2023-07-17 08:30 UTC, FelixTJDietrich commented on module_example/module_example/__main__.py
> +        emit_meta('_comment', 'You can add any meta data you want here')
I removed the underscore now

2023-07-17 08:39 UTC, FelixTJDietrich commented on playground/src/components/module_requests/request_submission_selection.tsx
> +        meta: {},
Done, thanks for the suggestion

2023-07-17 10:03 UTC, pal03377 commented on assessment_module_manager/assessment_module_manager/module/request_to_module.py
> +        pass
Yes 👍

2023-07-17 10:06 UTC, pal03377 approved these changes
Code looks good & I tested it again locally. Thanks for the contribution, very cool changes! I'll merge it right now

2023-07-17 10:06 UTC, merged